import fs from 'node:fs';

const examSubjects = {
  'JEE MAINS & ADVANCE': ['Physics', 'Chemistry', 'Mathematics'],
  NEET: ['Physics', 'Chemistry', 'Biology'],
  BOARDS: ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'Hindi', 'English'],
  CA: ['Accounting', 'Law', 'Economics', 'Taxation'],
  UPSC: ['History', 'Geography', 'Polity', 'Economics', 'General Science'],
  NDA: ['Mathematics', 'English', 'General Science', 'History', 'Geography'],
  SSC: ['Quantitative Aptitude', 'Reasoning', 'English', 'General Awareness'],
  CUET: ['General Test', 'English', 'General Knowledge', 'Reasoning', 'Mathematics'],
};

const quizExamKeys = {
  'JEE MAINS & ADVANCE': 'JEE',
  NEET: 'NEET',
  BOARDS: 'Board',
  CA: 'CA',
  UPSC: 'UPSC',
  NDA: 'NDA',
  SSC: 'SSC',
  CUET: 'CUET',
};

const questionTemplateBanks = {
  Physics: [
    ['The SI unit of force is:', ['Joule', 'Newton', 'Pascal', 'Watt'], 'Newton'],
    ['The SI unit of electric current is:', ['Volt', 'Ohm', 'Ampere', 'Joule'], 'Ampere'],
    ['A body moving with uniform acceleration covers 20 m in the first second and 30 m in the second second. What is its acceleration?', ['5 m/s²', '10 m/s²', '15 m/s²', '20 m/s²'], '10 m/s²'],
    ['The force required to keep an object moving in a circular path is called:', ['Centripetal force', 'Centrifugal force', 'Gravitational force', 'Frictional force'], 'Centripetal force'],
    ['Ohm\'s law is represented by:', ['V = IR', 'P = VI', 'F = ma', 'E = mc²'], 'V = IR'],
    ['The unit of power is:', ['Joule', 'Watt', 'Newton', 'Pascal'], 'Watt'],
    ['The speed of light in vacuum is approximately:', ['3 × 10⁷ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁵ m/s'], '3 × 10⁸ m/s'],
    ['A lens that converges light rays is called:', ['Concave lens', 'Convex lens', 'Plano-concave lens', 'Plano-convex lens'], 'Convex lens'],
    ['The resistance of a conductor depends mainly on:', ['Length and area of cross-section', 'Mass and volume', 'Temperature only', 'Charge only'], 'Length and area of cross-section'],
    ['The frequency of AC mains in India is:', ['50 Hz', '60 Hz', '100 Hz', '120 Hz'], '50 Hz'],
    ['The process of splitting a white light into colours is called:', ['Refraction', 'Dispersion', 'Reflection', 'Interference'], 'Dispersion'],
    ['The boiling point of water at normal pressure is:', ['90°C', '100°C', '110°C', '120°C'], '100°C'],
    ['Which quantity is measured in joules?', ['Power', 'Work', 'Velocity', 'Force'], 'Work'],
    ['The magnetic field lines around a bar magnet are:', ['Straight', 'Closed curves', 'Random', 'Parallel to the magnet'], 'Closed curves'],
    ['When a body is in equilibrium, net force acting on it is:', ['Zero', 'Maximum', 'Minimum', 'Infinite'], 'Zero'],
  ],
  Chemistry: [
    ['The pH of a neutral solution at 25°C is:', ['0', '7', '10', '14'], '7'],
    ['Which gas is produced when zinc reacts with dilute hydrochloric acid?', ['Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon dioxide'], 'Hydrogen'],
    ['The valency of oxygen is:', ['1', '2', '3', '4'], '2'],
    ['The atomic number of carbon is:', ['4', '6', '8', '12'], '6'],
    ['Which of the following is an alkali?', ['NaOH', 'HCl', 'CH₃OH', 'NaCl'], 'NaOH'],
    ['The chemical formula of ammonia is:', ['NH₃', 'N₂H₄', 'NH₄OH', 'NO₂'], 'NH₃'],
    ['Which element is a noble gas?', ['Nitrogen', 'Oxygen', 'Helium', 'Hydrogen'], 'Helium'],
    ['The process of conversion of liquid to gas is called:', ['Condensation', 'Evaporation', 'Sublimation', 'Freezing'], 'Evaporation'],
    ['The oxidation state of hydrogen in H₂O is:', ['-1', '0', '1', '2'], '1'],
    ['Which gas is essential for respiration?', ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Helium'], 'Oxygen'],
    ['The functional group of alcohols is:', ['-OH', '-COOH', '-CHO', '-NH₂'], '-OH'],
    ['The most reactive halogen is:', ['Cl', 'Br', 'F', 'I'], 'F'],
    ['Which acid is present in lemon juice?', ['Acetic acid', 'Citric acid', 'Hydrochloric acid', 'Sulphuric acid'], 'Citric acid'],
    ['The number of atoms in a molecule of water is:', ['1', '2', '3', '4'], '3'],
    ['Which of the following is a strong electrolyte?', ['Sugar solution', 'Acetic acid', 'NaCl solution', 'Distilled water'], 'NaCl solution'],
  ],
  Mathematics: [
    ['The derivative of x² + 3x + 2 is:', ['2x + 2', '2x + 3', 'x + 3', '3x + 2'], '2x + 3'],
    ['What is the value of sin 90°?', ['0', '1/2', '1', '√3/2'], '1'],
    ['The area of a triangle with base 10 and height 6 is:', ['30', '60', '16', '24'], '30'],
    ['The value of 5! is:', ['20', '60', '120', '720'], '120'],
    ['The sum of first 5 natural numbers is:', ['10', '15', '20', '25'], '15'],
    ['If x + 2 = 7, then x =', ['3', '4', '5', '6'], '5'],
    ['The slope of the line y = 3x + 2 is:', ['2', '3', '1/3', '-3'], '3'],
    ['The product of 3 and 7 is:', ['20', '21', '24', '28'], '21'],
    ['The HCF of 12 and 18 is:', ['2', '3', '6', '9'], '6'],
    ['The value of 2^5 is:', ['8', '16', '32', '64'], '32'],
    ['The median of 2, 5, 7, 9, 11 is:', ['5', '7', '9', '11'], '7'],
    ['The quadratic equation has degree:', ['1', '2', '3', '4'], '2'],
    ['The circumference of a circle of radius 7 is:', ['7π', '14π', '21π', '49π'], '14π'],
    ['If a = 2 and b = 3, then a² + b² =', ['5', '10', '13', '25'], '13'],
    ['The point (0,0) is called the:', ['Origin', 'Axis', 'Intercept', 'Vertex'], 'Origin'],
  ],
  Biology: [
    ['The powerhouse of the cell is:', ['Nucleus', 'Mitochondria', 'Golgi body', 'Ribosome'], 'Mitochondria'],
    ['The largest organ in the human body is:', ['Liver', 'Lung', 'Skin', 'Heart'], 'Skin'],
    ['Plants prepare food by the process of:', ['Respiration', 'Photosynthesis', 'Transpiration', 'Fermentation'], 'Photosynthesis'],
    ['Human blood is red because of:', ['Plasma', 'Haemoglobin', 'Platelets', 'Lymph'], 'Haemoglobin'],
    ['The human heart has how many chambers?', ['2', '3', '4', '5'], '4'],
    ['The female reproductive organ in plants is:', ['Stamen', 'Pistil', 'Petal', 'Leaf'], 'Pistil'],
    ['Which blood cells help in clotting?', ['RBCs', 'WBCs', 'Platelets', 'Plasma'], 'Platelets'],
    ['The process of conversion of glucose into energy in cells is called:', ['Respiration', 'Digestion', 'Osmosis', 'Excretion'], 'Respiration'],
    ['The function of roots is to:', ['Prepare food', 'Absorb water', 'Attract insects', 'Store chlorophyll'], 'Absorb water'],
    ['The organ that filters blood is:', ['Liver', 'Lungs', 'Kidney', 'Pancreas'], 'Kidney'],
    ['DNA stands for:', ['Deoxyribonucleic acid', 'Dioxyribonucleic acid', 'Double ribose acid', 'Digenetic nucleic acid'], 'Deoxyribonucleic acid'],
    ['The site of protein synthesis in a cell is:', ['Mitochondria', 'Ribosome', 'Nucleus', 'Vacuole'], 'Ribosome'],
    ['The vitamin produced by sunlight is:', ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], 'Vitamin D'],
    ['The type of blood vessel carrying blood away from the heart is:', ['Vein', 'Capillary', 'Artery', 'Lymph'], 'Artery'],
    ['The process by which plants lose water is called:', ['Photosynthesis', 'Transpiration', 'Respiration', 'Pollination'], 'Transpiration'],
  ],
  English: [
    ['Synonym of brave is:', ['Cowardly', 'Fearless', 'Lazy', 'Weak'], 'Fearless'],
    ['Antonym of ancient is:', ['Old', 'Modern', 'Rich', 'Tall'], 'Modern'],
    ['She ___ to school every day.', ['go', 'goes', 'gone', 'going'], 'goes'],
    ['The red car is fast. Identify adjective:', ['car', 'red', 'fast', 'is'], 'red'],
    ['Plural of child is:', ['Childs', 'Childes', 'Children', 'Childrens'], 'Children'],
    ['Passive of “They completed the task” is:', ['The task is completed', 'The task was completed by them', 'They were completed', 'The task had completed'], 'The task was completed by them'],
    ['He is too weak ___ walk.', ['for', 'to', 'so', 'and'], 'to'],
    ['Correct spelling is:', ['Receved', 'Recieved', 'Received', 'Receeved'], 'Received'],
    ['A stitch in time saves nine means:', ['Delay is good', 'Prompt action prevents bigger problems', 'Time is money', 'Work is easy'], 'Prompt action prevents bigger problems'],
    ['___ apple a day keeps the doctor away.', ['A', 'An', 'The', 'No article'], 'An'],
    ['I have finished ___ work.', ['my', 'mine', 'me', 'I'], 'my'],
    ['If I ___ you, I would help.', ['am', 'was', 'were', 'be'], 'were'],
    ['Opposite of difficult is:', ['Hard', 'Easy', 'Strict', 'Heavy'], 'Easy'],
    ['Noun form of happy is:', ['Happily', 'Happiness', 'Happier', 'Happiest'], 'Happiness'],
    ['Correct sentence is:', ['He do not know', 'He does not know', 'He not know', 'He did not knew'], 'He does not know'],
  ],
  Hindi: [
    ['“साक्षर” का विलोम है:', ['असाक्षर', 'साफ', 'शिक्षित', 'कठिन'], 'असाक्षर'],
    ['“दीपक” का पर्यायवाची है:', ['चाँद', 'प्रकाश', 'पवन', 'आकाश'], 'प्रकाश'],
    ['“सूरज” का बहुवचन है:', ['सूरजों', 'सूरज', 'सूरजें', 'सूरजाए'], 'सूरजों'],
    ['“कृपा” का अर्थ है:', ['दया', 'क्रोध', 'घबराहट', 'जुनून'], 'दया'],
    ['“आकाश” का सही व्याकरण रूप है:', ['आकाश', 'आकाशीय', 'आकाशा', 'आकाशें'], 'आकाश'],
    ['“गगन” का संधि-विच्छेद है:', ['ग + गन', 'गग + न', 'ग + अ + न', 'गगन'], 'ग + गन'],
    ['“लिखना” का भूतकाल है:', ['लिखा', 'लिखता', 'लिखें', 'लिखेंगें'], 'लिखा'],
    ['“सुन्दर” का विलोम है:', ['असुन्दर', 'कठिन', 'दुःख', 'उच्च'], 'असुन्दर'],
    ['“किताब” का बहुवचन है:', ['किताबें', 'किताबों', 'किताब', 'किताबे'], 'किताबों'],
    ['“मैं स्कूल जा रहा हूँ” में सर्वनाम है:', ['मैं', 'स्कूल', 'जा', 'रहा'], 'मैं'],
    ['“मधुर” का विलोम है:', ['उत्साह', 'कड़वा', 'सुगम', 'उच्च'], 'कड़वा'],
    ['“बालक” का पर्यायवाची है:', ['बच्चा', 'पेड़', 'कागज', 'गाँव'], 'बच्चा'],
    ['“कर्म” का तद्भव शब्द है:', ['काम', 'कार्य', 'कर्मा', 'करना'], 'कार्य'],
    ['“अच्छा” का तद्भव रूप है:', ['बेहतर', 'भला', 'सुन्दर', 'उत्तम'], 'भला'],
    ['“सुनना” का सही रूप है:', ['सुनना', 'सुनो', 'सुनने', 'सुनता है'], 'सुनना'],
  ],
  Accounting: [
    ['The accounting equation is:', ['Assets = Liabilities + Capital', 'Assets + Liabilities = Capital', 'Assets = Capital - Liabilities', 'Liabilities = Assets + Capital'], 'Assets = Liabilities + Capital'],
    ['The process of recording financial transactions is called:', ['Posting', 'Journalising', 'Balancing', 'Auditing'], 'Journalising'],
    ['Goods withdrawn by the proprietor for personal use are called:', ['Sales return', 'Drawings', 'Purchases', 'Expenses'], 'Drawings'],
    ['The statement showing financial position at a point in time is:', ['Profit and Loss Account', 'Cash Flow Statement', 'Balance Sheet', 'Trial Balance'], 'Balance Sheet'],
    ['Depreciation is charged to:', ['Trading Account', 'Profit and Loss Account', 'Cash Account', 'Capital Account'], 'Profit and Loss Account'],
    ['Which book records all credit purchases?', ['Cash Book', 'Purchase Book', 'Sales Book', 'Journal Proper'], 'Purchase Book'],
    ['A debit balance in the bank passbook indicates:', ['Bank overdraft', 'Excess credit balance', 'No effect', 'Cash underflow'], 'Bank overdraft'],
    ['An asset converted into cash within a year is called:', ['Fixed asset', 'Current asset', 'Intangible asset', 'Fictitious asset'], 'Current asset'],
    ['The primary objective of accounting is to:', ['Reduce taxes', 'Record and communicate financial information', 'Avoid expenses', 'Increase liabilities'], 'Record and communicate financial information'],
    ['Bad debts are treated as:', ['Capital expenditure', 'Operating expense', 'Investing activity', 'Non-current liability'], 'Operating expense'],
    ['The trial balance is prepared to check:', ['Correctness of arithmetic of ledger balances', 'Cash flow timing', 'Market valuation', 'Tax impact'], 'Correctness of arithmetic of ledger balances'],
    ['A credit balance in a personal account means the holder is:', ['A debtor', 'A creditor', 'A banker', 'A shareholder'], 'A creditor'],
    ['The amount invested by the owner is called:', ['Loan', 'Drawings', 'Capital', 'Revenue'], 'Capital'],
    ['The financial statement used to understand liquidity is:', ['Cash flow statement', 'Balance sheet', 'Trading account', 'Income statement'], 'Cash flow statement'],
    ['The concept of recording at historical cost is known as:', ['Entity concept', 'Historical cost concept', 'Matching concept', 'Going concern'], 'Historical cost concept'],
  ],
  Law: [
    ['The Constitution of India came into force on:', ['15 August 1947', '26 January 1950', '2 October 1945', '1 January 1952'], '26 January 1950'],
    ['The Right to Equality is guaranteed under:', ['Article 14', 'Article 19', 'Article 21', 'Article 32'], 'Article 14'],
    ['The Supreme Court of India is the:', ['Highest appellate court', 'Only revenue court', 'Parliamentary body', 'Executive court'], 'Highest appellate court'],
    ['A contract is enforceable by:', ['Morality', 'Custom', 'Law', 'Society'], 'Law'],
    ['The head of the State in India is:', ['Prime Minister', 'President', 'Chief Justice', 'Attorney General'], 'President'],
    ['Rule of law is associated with:', ['Dicey', 'Marx', 'Hobbes', 'Aristotle'], 'Dicey'],
    ['The minimum age for President is:', ['18 years', '21 years', '25 years', '35 years'], '35 years'],
    ['A contract without free consent is:', ['Valid', 'Voidable', 'Void', 'Legal'], 'Voidable'],
    ['The Right to Freedom of Speech is in:', ['Article 19', 'Article 21', 'Article 17', 'Article 26'], 'Article 19'],
    ['A person entering into a contract is called a:', ['Witness', 'Party', 'Judge', 'Notary'], 'Party'],
    ['Judicial review in India is based on:', ['Separation of powers', 'Judicial supremacy', 'Federalism', 'Executive supremacy'], 'Judicial supremacy'],
    ['The concept of Directive Principles is inspired by:', ['USA', 'Britain', 'Ireland', 'Canada'], 'Ireland'],
    ['An agreement to do an impossible act is:', ['Valid', 'Void', 'Voidable', 'Enforceable'], 'Void'],
    ['The legal responsibility for a tort is imposed on:', ['The state only', 'The wrongdoer', 'The witness', 'The parliament'], 'The wrongdoer'],
    ['The Constitution is known as the:', ['Temporary law', 'Supreme law of the land', 'Executive order', 'Judicial opinion'], 'Supreme law of the land'],
  ],
  Economics: [
    ['Economics is mainly concerned with:', ['Wealth only', 'Human behaviour in relation to choices', 'Government control', 'Military strategy'], 'Human behaviour in relation to choices'],
    ['The fundamental economic problem is:', ['Inflation', 'Scarcity', 'Deflation', 'Monopoly'], 'Scarcity'],
    ['Demand falls when:', ['Price falls', 'Price rises', 'Income falls', 'Population falls'], 'Price rises'],
    ['GDP measures:', ['Total value of production', 'Government spending only', 'Tax revenue', 'Foreign trade'], 'Total value of production'],
    ['Inflation refers to:', ['Fall in prices', 'Rise in general price level', 'Stable prices', 'Decrease in wages'], 'Rise in general price level'],
    ['Opportunity cost means:', ['Cost of labour', 'Next best alternative forgone', 'Fixed cost', 'Marketing cost'], 'Next best alternative forgone'],
    ['The central bank of India is:', ['ICICI', 'SBI', 'RBI', 'PNB'], 'RBI'],
    ['Fiscal policy relates to:', ['Interest rate', 'Taxation and public expenditure', 'Currency supply', 'Import policy'], 'Taxation and public expenditure'],
    ['A market with one seller is called:', ['Monopoly', 'Oligopoly', 'Monopsony', 'Perfect competition'], 'Monopoly'],
    ['When total utility is maximum, marginal utility is:', ['Positive', 'Zero', 'Negative', 'Infinite'], 'Zero'],
    ['The main cause of unemployment is:', ['Low inflation', 'Lack of demand', 'High exports', 'Low taxes'], 'Lack of demand'],
    ['Elasticity of demand is:', ['Percentage change in quantity demanded over percentage change in price', 'Total revenue minus cost', 'Supply minus demand', 'Average cost'], 'Percentage change in quantity demanded over percentage change in price'],
    ['The primary sector includes:', ['Agriculture and mining', 'Manufacturing', 'Trade', 'Banking'], 'Agriculture and mining'],
    ['Equilibrium price is where:', ['Quantity demanded = quantity supplied', 'Demand is zero', 'Supply exceeds demand', 'Government fixes it'], 'Quantity demanded = quantity supplied'],
    ['The budget is prepared by:', ['RBI', 'Finance Ministry', 'SEBI', 'NITI Aayog'], 'Finance Ministry'],
  ],
  Taxation: [
    ['Income tax is a:', ['Indirect tax', 'Direct tax', 'Customs duty', 'Service tax'], 'Direct tax'],
    ['GST was implemented in India in:', ['2015', '2017', '2019', '2021'], '2017'],
    ['The tax collected by sellers and paid to government is:', ['Income tax', 'GST', 'Property tax', 'Wealth tax'], 'GST'],
    ['Tax burden of indirect taxes is usually borne by:', ['Government', 'Consumers', 'Employers', 'Investors'], 'Consumers'],
    ['Corporate tax is a:', ['Direct tax', 'Indirect tax', 'Excise duty', 'Custom duty'], 'Direct tax'],
    ['Tax evasion is:', ['Legal planning', 'Illegal non-payment of tax', 'Tax refund', 'Tax subsidy'], 'Illegal non-payment of tax'],
    ['The authority that collects GST in India is:', ['SEBI', 'RBI', 'CBIC', 'NSE'], 'CBIC'],
    ['Taxable income means:', ['Gross income before deductions', 'Total income minus deductions', 'Tax rate', 'Sales revenue'], 'Total income minus deductions'],
    ['Tax incidence refers to:', ['Who bears the burden of tax', 'Tax refund amount', 'Tax rate', 'Tax collection date'], 'Who bears the burden of tax'],
    ['Customs duty is imposed on:', ['Domestic sales', 'Goods imported', 'Salary', 'Bank deposits'], 'Goods imported'],
    ['The purpose of taxation is to:', ['Increase profits', 'Generate revenue for public expenditure', 'Reduce imports', 'Increase wages'], 'Generate revenue for public expenditure'],
    ['A tax on the supply of goods and services is:', ['Income tax', 'Property tax', 'GST', 'Gift tax'], 'GST'],
    ['The burden of indirect tax is generally on:', ['Producers only', 'Consumers', 'Government', 'Shareholders'], 'Consumers'],
    ['Taxable income can be reduced by:', ['Claiming deductions', 'Increasing sales', 'Borrowing', 'Ignoring income'], 'Claiming deductions'],
    ['Which is a direct tax?', ['GST', 'Corporate tax', 'VAT', 'Service tax'], 'Corporate tax'],
  ],
  History: [
    ['The Indian National Congress was founded in:', ['1885', '1905', '1919', '1942'], '1885'],
    ['The Non-Cooperation Movement was launched in:', ['1919', '1920', '1928', '1930'], '1920'],
    ['The Great Revolt of 1857 began at:', ['Meerut', 'Lucknow', 'Jhansi', 'Gwalior'], 'Meerut'],
    ['The first battle of Panipat was fought in:', ['1526', '1556', '1618', '1761'], '1526'],
    ['The slogan “Do or Die” is associated with:', ['Quit India Movement', 'Civil Disobedience Movement', 'Home Rule Movement', 'Swadeshi Movement'], 'Quit India Movement'],
    ['Who wrote “Discovery of India”?', ['Subhas Bose', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Rabindranath Tagore'], 'Jawaharlal Nehru'],
    ['The Simon Commission was boycotted because it had:', ['No Indian representation', 'No British officers', 'No evidence', 'No report'], 'No Indian representation'],
    ['The first Mughal emperor was:', ['Akbar', 'Babur', 'Humayun', 'Aurangzeb'], 'Babur'],
    ['The Salt Satyagraha was led by:', ['Jawaharlal Nehru', 'Mahatma Gandhi', 'B.R. Ambedkar', 'Sardar Patel'], 'Mahatma Gandhi'],
    ['The Constitution came into force on:', ['15 August 1947', '26 January 1950', '26 November 1949', '1 April 1950'], '26 January 1950'],
    ['The title “Tiger of Mysore” was given to:', ['Tipu Sultan', 'Shivaji', 'Akbar', 'Aurangzeb'], 'Tipu Sultan'],
    ['Who was the last Mughal emperor?', ['Akbar', 'Bahadur Shah Zafar', 'Shah Jahan', 'Jahangir'], 'Bahadur Shah Zafar'],
    ['The Bhakti saint Kabir was associated with:', ['Brahmo Samaj', 'Sufism', 'Arya Samaj', 'Renaissance'], 'Sufism'],
    ['The famous Revolt of 1857 began in:', ['Kanpur', 'Meerut', 'Jhansi', 'Delhi'], 'Meerut'],
    ['The Quit India Movement started in:', ['1940', '1942', '1945', '1947'], '1942'],
  ],
  Geography: [
    ['The Himalayas are an example of:', ['Fold mountains', 'Block mountains', 'Volcanic mountains', 'Residual mountains'], 'Fold mountains'],
    ['The longest river in India is:', ['Godavari', 'Ganga', 'Indus', 'Brahmaputra'], 'Ganga'],
    ['The largest desert in India is:', ['Thar', 'Kalahari', 'Gobi', 'Sahara'], 'Thar'],
    ['Which state has the longest coastline?', ['Gujarat', 'Tamil Nadu', 'Kerala', 'Andhra Pradesh'], 'Gujarat'],
    ['The Tropic of Cancer passes through:', ['Gujarat', 'Kerala', 'Tamil Nadu', 'West Bengal'], 'Gujarat'],
    ['The highest waterfall in India is:', ['Jog Falls', 'Dudhsagar', 'Kunchikal', 'Nohkalikai'], 'Kunchikal'],
    ['The climate of India is shaped mainly by:', ['Monsoon and latitude', 'Polar winds only', 'Ocean currents only', 'Volcanic activity'], 'Monsoon and latitude'],
    ['The largest lake in India is:', ['Wular Lake', 'Chilka', 'Vembanad', 'Sambhar'], 'Wular Lake'],
    ['The Deccan Plateau is located in:', ['Northern India', 'Southern India', 'Eastern India', 'Western India'], 'Southern India'],
    ['Which soil is best for cotton?', ['Alluvial', 'Black', 'Laterite', 'Red'], 'Black'],
    ['Western disturbances cause:', ['Winter rainfall in North India', 'Monsoon winds', 'Coastal erosion', 'Desert storms'], 'Winter rainfall in North India'],
    ['The state called “Land of Five Rivers” is:', ['Punjab', 'Haryana', 'Jammu and Kashmir', 'Uttar Pradesh'], 'Punjab'],
    ['The Nilgiri Hills are in:', ['Tamil Nadu', 'Himachal Pradesh', 'Odisha', 'Arunachal'], 'Tamil Nadu'],
    ['The smallest state by area is:', ['Goa', 'Sikkim', 'Tripura', 'Manipur'], 'Goa'],
    ['The evergreen forests are mainly found in:', ['Western Ghats and North East', 'Thar', 'Indo-Gangetic plains', 'Himalayan region'], 'Western Ghats and North East'],
  ],
  Polity: [
    ['The Preamble begins with:', ['We the People of India', 'We the Citizens of India', 'We the Sovereign People', 'We the Nation'], 'We the People of India'],
    ['Right to Equality is in:', ['Article 14', 'Article 19', 'Article 21', 'Article 32'], 'Article 14'],
    ['The Constitutional head of the Union is:', ['Prime Minister', 'President', 'Chief Justice', 'Speaker'], 'President'],
    ['The Parliament consists of:', ['Lok Sabha and Rajya Sabha', 'Lok Sabha and Supreme Court', 'State Assemblies', 'Judiciary and Cabinet'], 'Lok Sabha and Rajya Sabha'],
    ['Directive Principles are borrowed from:', ['USA', 'Canada', 'Ireland', 'Britain'], 'Ireland'],
    ['Who appoints the Prime Minister?', ['Parliament', 'President', 'Supreme Court', 'Election Commission'], 'President'],
    ['Judicial review is exercised by:', ['Parliament', 'Executive', 'Judiciary', 'Election Commission'], 'Judiciary'],
    ['The Governor is appointed by:', ['Chief Minister', 'President', 'Prime Minister', 'Supreme Court'], 'President'],
    ['The CAG is appointed by:', ['President', 'Prime Minister', 'Parliament', 'Finance Ministry'], 'President'],
    ['Single citizenship exists in:', ['USA', 'Canada', 'India', 'Australia'], 'India'],
    ['The number of Schedules in the Constitution is:', ['11', '12', '13', '15'], '12'],
    ['The first session of the Constituent Assembly was held in:', ['1946', '1947', '1948', '1949'], '1946'],
    ['The phrase “Justice, Liberty, Equality, Fraternity” appears in:', ['Preamble', 'Directive Principles', 'Fundamental Duties', 'Federal Structure'], 'Preamble'],
    ['Which body conducts Lok Sabha elections?', ['Supreme Court', 'Election Commission', 'Parliamentary Committee', 'Cabinet'], 'Election Commission'],
    ['Right to Life is in:', ['Article 19', 'Article 21', 'Article 32', 'Article 51A'], 'Article 21'],
  ],
  'General Science': [
    ['Plants prepare food by:', ['Respiration', 'Photosynthesis', 'Transpiration', 'Fermentation'], 'Photosynthesis'],
    ['The SI unit of force is:', ['Joule', 'Newton', 'Pascal', 'Watt'], 'Newton'],
    ['Blood cells helping clotting are:', ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], 'Platelets'],
    ['Largest organ of human body is:', ['Liver', 'Lung', 'Skin', 'Stomach'], 'Skin'],
    ['Atomic number of carbon is:', ['6', '8', '12', '14'], '6'],
    ['The gas most abundant in atmosphere is:', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 'Nitrogen'],
    ['Speed of light is approx:', ['3 x 10^5 m/s', '3 x 10^8 m/s', '3 x 10^10 m/s', '3 x 10^2 m/s'], '3 x 10^8 m/s'],
    ['The powerhouse of the cell is:', ['Nucleus', 'Mitochondria', 'Golgi body', 'Ribosome'], 'Mitochondria'],
    ['Chemical formula of water is:', ['H2O2', 'HO2', 'H2O', 'OH2'], 'H2O'],
    ['Renewable energy source is:', ['Coal', 'Petroleum', 'Solar energy', 'Natural gas'], 'Solar energy'],
    ['Human heart has:', ['2 chambers', '3 chambers', '4 chambers', '5 chambers'], '4 chambers'],
    ['Vitamin produced by sunlight is:', ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], 'Vitamin D'],
    ['Liquid to vapour is:', ['Condensation', 'Evaporation', 'Fusion', 'Sublimation'], 'Evaporation'],
    ['Red planet is:', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 'Mars'],
    ['pH of pure water is:', ['0', '7', '10', '14'], '7'],
  ],
  'Quantitative Aptitude': [
    ['Average of 4, 6, 8, 10 is:', ['6', '7', '8', '9'], '7'],
    ['25% of 200 is:', ['25', '50', '75', '100'], '50'],
    ['60 km/h for 180 km takes:', ['2 hours', '3 hours', '4 hours', '5 hours'], '3 hours'],
    ['If 8x = 32 then x is:', ['2', '3', '4', '5'], '4'],
    ['Simple interest on ₹1000 at 10% for 2 years is:', ['₹100', '₹200', '₹300', '₹400'], '₹200'],
    ['The ratio of 12 to 18 is:', ['2:3', '3:2', '1:2', '4:3'], '2:3'],
    ['Perimeter of a 5 cm by 3 cm rectangle is:', ['8 cm', '12 cm', '15 cm', '16 cm'], '16 cm'],
    ['The square of 9 is:', ['18', '27', '81', '99'], '81'],
    ['The cube root of 64 is:', ['2', '4', '6', '8'], '4'],
    ['Probability of head on fair coin toss is:', ['0', '1/2', '1', '2'], '1/2'],
    ['If a = 5, b = 3, then a² - b² = ?', ['8', '12', '16', '25'], '16'],
    ['The cost price of an item sold for ₹120 at a 20% profit is:', ['₹90', '₹100', '₹110', '₹120'], '₹100'],
    ['The LCM of 6 and 8 is:', ['12', '18', '24', '48'], '24'],
    ['The value of 7 × 8 ÷ 2 is:', ['14', '28', '56', '7'], '28'],
    ['15% of 200 is:', ['15', '20', '30', '40'], '30'],
  ],
  Reasoning: [
    ['Odd one out: 2, 3, 5, 7, 9', ['2', '3', '5', '9'], '9'],
    ['A is taller than B and B is taller than C. Who is tallest?', ['A', 'B', 'C', 'Cannot say'], 'A'],
    ['Complete the series: 3, 6, 9, 12, ?', ['13', '14', '15', '16'], '15'],
    ['Which is a vowel?', ['B', 'C', 'E', 'M'], 'E'],
    ['If all roses are flowers and some flowers are red, which statement is definitely true?', ['All roses are red', 'Some roses are red', 'All flowers are roses', 'Some flowers are roses'], 'Some flowers are roses'],
    ['Arrange in logical order: Seed, Plant, Flower, Fruit', ['Seed, Flower, Plant, Fruit', 'Seed, Plant, Flower, Fruit', 'Flower, Seed, Plant, Fruit', 'Plant, Seed, Flower, Fruit'], 'Seed, Plant, Flower, Fruit'],
    ['Which number comes next: 1, 4, 9, 16, ?', ['20', '24', '25', '36'], '25'],
    ['If 1 = A, 2 = B, 3 = C, then 4 = ?', ['D', 'E', 'F', 'G'], 'D'],
    ['Pointing to a girl, Raj says, “She is my sister’s daughter.” How is the girl related to Raj?', ['Daughter', 'Niece', 'Cousin', 'Granddaughter'], 'Niece'],
    ['Choose the odd one out: Sun, Moon, Earth, Mars', ['Sun', 'Moon', 'Earth', 'Mars'], 'Moon'],
    ['Which comes next: AB, CD, EF, ?', ['GH', 'IJ', 'KL', 'MN'], 'GH'],
    ['If today is Monday, what day will it be after 10 days?', ['Tuesday', 'Wednesday', 'Thursday', 'Friday'], 'Thursday'],
    ['Which word does not belong: Book, Pen, Table, Paper', ['Book', 'Pen', 'Table', 'Paper'], 'Table'],
    ['If all dogs bark and Max is a dog, then:', ['Max does not bark', 'Max can bark', 'Max is a cat', 'Max sings'], 'Max can bark'],
    ['Find the missing number: 5, 10, 20, 40, ?', ['50', '60', '80', '100'], '80'],
  ],
  'General Awareness': [
    ['Who is known as the Father of the Nation in India?', ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'Bhagat Singh'], 'Mahatma Gandhi'],
    ['The capital of Japan is:', ['Seoul', 'Tokyo', 'Beijing', 'Bangkok'], 'Tokyo'],
    ['The currency of the United Kingdom is:', ['Dollar', 'Euro', 'Pound Sterling', 'Yen'], 'Pound Sterling'],
    ['The largest planet in the solar system is:', ['Earth', 'Mars', 'Jupiter', 'Saturn'], 'Jupiter'],
    ['Who wrote the National Anthem “Jana Gana Mana”?', ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarojini Naidu', 'Subhas Chandra Bose'], 'Rabindranath Tagore'],
    ['The headquarters of the United Nations is in:', ['Geneva', 'New York', 'Paris', 'Rome'], 'New York'],
    ['Which is the largest mammal?', ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'], 'Blue whale'],
    ['Who is known as the Missile Man of India?', ['APJ Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha', 'Raja Ramanna'], 'APJ Abdul Kalam'],
    ['The longest river in the world is:', ['Nile', 'Amazon', 'Ganga', 'Yangtze'], 'Amazon'],
    ['Which gas do plants absorb?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 'Carbon dioxide'],
    ['The Parliament of India is located in:', ['Mumbai', 'New Delhi', 'Chennai', 'Kolkata'], 'New Delhi'],
    ['The term “Bharat” appears in the constitution in:', ['Preamble', 'Fundamental Rights', 'Directive Principles', 'Schedules'], 'Preamble'],
    ['Who discovered gravity?', ['Galileo', 'Newton', 'Einstein', 'Kepler'], 'Newton'],
    ['The smallest continent is:', ['Europe', 'Australia', 'Antarctica', 'South America'], 'Australia'],
    ['The number of states in India is:', ['24', '28', '29', '30'], '28'],
  ],
  'General Test': [
    ['If 12 workers complete a task in 8 days, how many days will 6 workers take?', ['12 days', '14 days', '16 days', '18 days'], '16 days'],
    ['The average of 10, 20, 30 is:', ['15', '20', '25', '30'], '20'],
    ['A train runs at 72 km/h. In 15 minutes it covers:', ['12 km', '18 km', '24 km', '30 km'], '18 km'],
    ['Which is the next term: 1, 3, 6, 10, 15, ?', ['20', '21', '24', '25'], '21'],
    ['The percentage equivalent of 1/4 is:', ['20%', '25%', '50%', '75%'], '25%'],
    ['A shopkeeper marks a product at ₹500 and gives 10% discount. Selling price is:', ['₹450', '₹470', '₹480', '₹490'], '₹450'],
    ['The HCF of 18 and 24 is:', ['2', '3', '6', '12'], '6'],
    ['Which is the odd one out: 8, 27, 64, 125, 216?', ['8', '27', '64', '216'], '216'],
    ['If all men are honest and Ravi is a man, Ravi is:', ['dishonest', 'honest', 'rich', 'poor'], 'honest'],
    ['Which of the following is a prime number?', ['21', '29', '33', '39'], '29'],
    ['The area of a square with side 5 cm is:', ['10 cm²', '20 cm²', '25 cm²', '30 cm²'], '25 cm²'],
    ['The correct order of the planets from the sun is:', ['Mercury, Venus, Earth, Mars', 'Venus, Mercury, Earth, Mars', 'Earth, Venus, Mercury, Mars', 'Mars, Earth, Venus, Mercury'], 'Mercury, Venus, Earth, Mars'],
    ['Which word is the opposite of “sincere”?', ['Honest', 'Dishonest', 'Trustworthy', 'Friendly'], 'Dishonest'],
    ['The value of 15 × 2 + 10 is:', ['20', '25', '30', '40'], '40'],
    ['If north is opposite to south, then east is opposite to:', ['North', 'South', 'West', 'East'], 'West'],
  ],
  'General Knowledge': [
    ['Who is the current President of India?', ['Ram Nath Kovind', 'Pratibha Patil', 'Droupadi Murmu', 'Narendra Modi'], 'Droupadi Murmu'],
    ['The capital of Karnataka is:', ['Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru'], 'Bengaluru'],
    ['The currency of France is:', ['Dollar', 'Rupee', 'Euro', 'Yen'], 'Euro'],
    ['The largest river in India is:', ['Yamuna', 'Ganga', 'Godavari', 'Krishna'], 'Ganga'],
    ['The national animal of India is:', ['Lion', 'Tiger', 'Elephant', 'Gaur'], 'Tiger'],
    ['Who painted the Mona Lisa?', ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'], 'Leonardo da Vinci'],
    ['The smallest planet in the solar system is:', ['Mercury', 'Mars', 'Venus', 'Earth'], 'Mercury'],
    ['The headquarters of the World Health Organization is in:', ['Geneva', 'Paris', 'Rome', 'New York'], 'Geneva'],
    ['The national game of India is:', ['Cricket', 'Hockey', 'Football', 'Kabaddi'], 'Hockey'],
    ['Which festival is known as the festival of lights?', ['Holi', 'Diwali', 'Navratri', 'Id'], 'Diwali'],
    ['Who discovered radioactivity?', ['Marie Curie', 'Isaac Newton', 'Albert Einstein', 'Rosalind Franklin'], 'Marie Curie'],
    ['The largest continent is:', ['Africa', 'Europe', 'Asia', 'North America'], 'Asia'],
    ['The first man to walk on the moon was:', ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], 'Neil Armstrong'],
    ['The national bird of India is:', ['Peacock', 'Parrot', 'Eagle', 'Sparrow'], 'Peacock'],
    ['The Indian Constitution came into effect on:', ['15 August 1947', '26 January 1950', '2 October 1945', '1 January 1948'], '26 January 1950'],
  ],
};

const questionExtensions = {
  Physics: [
    ['A particle starts from rest with acceleration 2 m/s². Its displacement in 5 seconds is:', ['10 m', '20 m', '25 m', '50 m'], '25 m'],
    ['Two resistors of 6 Ω and 3 Ω are connected in parallel. Their equivalent resistance is:', ['1 Ω', '2 Ω', '3 Ω', '9 Ω'], '2 Ω'],
    ['A wave has frequency 50 Hz and wavelength 6 m. Its speed is:', ['8.33 m/s', '56 m/s', '300 m/s', '600 m/s'], '300 m/s'],
    ['If the momentum of a body is doubled while its mass is constant, its kinetic energy becomes:', ['Half', 'Double', 'Four times', 'Unchanged'], 'Four times'],
    ['In a transformer, the device that increases voltage is called a:', ['Step-down transformer', 'Step-up transformer', 'Rectifier', 'Oscillator'], 'Step-up transformer'],
  ],
  Chemistry: [
    ['For a first-order reaction, the unit of rate constant is:', ['mol L⁻¹ s⁻¹', 's⁻¹', 'L mol⁻¹ s⁻¹', 'mol² L⁻² s⁻¹'], 's⁻¹'],
    ['The hybridisation of carbon in methane is:', ['sp', 'sp²', 'sp³', 'dsp²'], 'sp³'],
    ['The electrode potential of a standard hydrogen electrode is:', ['1 V', '0 V', '-1 V', '0.5 V'], '0 V'],
    ['Which compound gives a positive iodoform test?', ['Methanol', 'Ethanol', 'Propanol', 'Benzene'], 'Ethanol'],
    ['The oxidation number of chromium in K₂Cr₂O₇ is:', ['+2', '+3', '+6', '+7'], '+6'],
  ],
  Mathematics: [
    ['If the roots of x² - 5x + 6 = 0 are α and β, then α² + β² equals:', ['11', '13', '25', '36'], '13'],
    ['The probability of getting at least one head in two tosses of a fair coin is:', ['1/4', '1/2', '3/4', '1'], '3/4'],
    ['The integral ∫2x dx is:', ['x² + C', '2x² + C', 'x + C', 'x²/2 + C'], 'x² + C'],
    ['The distance between (1, 2) and (4, 6) is:', ['3', '4', '5', '6'], '5'],
    ['The determinant of [[2, 1], [3, 4]] is:', ['5', '6', '8', '11'], '5'],
  ],
  Biology: [
    ['The enzyme that joins Okazaki fragments is:', ['Helicase', 'Ligase', 'Primase', 'Amylase'], 'Ligase'],
    ['The light reaction of photosynthesis occurs in the:', ['Stroma', 'Thylakoid membrane', 'Nucleus', 'Mitochondrial matrix'], 'Thylakoid membrane'],
    ['The hormone responsible for milk ejection is:', ['Prolactin', 'Oxytocin', 'Thyroxine', 'Insulin'], 'Oxytocin'],
    ['A dihybrid cross typically produces a phenotypic ratio of:', ['1:1', '3:1', '9:3:3:1', '1:2:1'], '9:3:3:1'],
    ['The functional unit of the kidney is:', ['Neuron', 'Nephron', 'Alveolus', 'Villus'], 'Nephron'],
  ],
  English: [
    ['Choose the correct transformation: “No other metal is as useful as iron.”', ['Iron is more useful than all metals', 'Iron is one of the most useful metals', 'All metals are useful as iron', 'Iron is not useful'], 'Iron is one of the most useful metals'],
    ['Choose the correctly spelt word:', ['Accomodation', 'Accommodation', 'Acommodation', 'Accommadation'], 'Accommodation'],
    ['The phrase “to hit the nail on the head” means:', ['To miss the point', 'To say exactly the right thing', 'To work with tools', 'To cause damage'], 'To say exactly the right thing'],
    ['Identify the figure of speech: “The wind whispered through the trees.”', ['Simile', 'Personification', 'Metonymy', 'Irony'], 'Personification'],
    ['Choose the correct indirect speech: She said, “I have completed the work.”', ['She said that she completed the work', 'She said that she had completed the work', 'She says she completed work', 'She said that I have completed work'], 'She said that she had completed the work'],
  ],
  Hindi: [
    ['“जो मेहनत करता है वही सफल होता है” वाक्य है:', ['सरल वाक्य', 'संयुक्त वाक्य', 'मिश्र वाक्य', 'विस्मयादिबोधक'], 'मिश्र वाक्य'],
    ['“निराशा” शब्द में उपसर्ग है:', ['नि', 'निर्', 'आ', 'शा'], 'निर्'],
    ['“राजपुत्र” का समास है:', ['द्वंद्व', 'तत्पुरुष', 'बहुव्रीहि', 'अव्ययीभाव'], 'तत्पुरुष'],
    ['“कमल-सा मुख” में अलंकार है:', ['रूपक', 'उपमा', 'अनुप्रास', 'यमक'], 'उपमा'],
    ['“आँखों का तारा” मुहावरे का अर्थ है:', ['बहुत प्रिय', 'बहुत दूर', 'बहुत क्रोधित', 'बहुत छोटा'], 'बहुत प्रिय'],
  ],
  Accounting: [
    ['A bank reconciliation statement is prepared to reconcile:', ['Cash book and passbook balances', 'Sales and purchases', 'Assets and liabilities', 'Capital and drawings'], 'Cash book and passbook balances'],
    ['Outstanding expenses are shown as:', ['Current assets', 'Current liabilities', 'Capital receipts', 'Drawings'], 'Current liabilities'],
    ['Goodwill is classified as a:', ['Tangible asset', 'Intangible asset', 'Current liability', 'Fictitious liability'], 'Intangible asset'],
    ['The matching concept requires expenses to be matched with:', ['Assets', 'Related revenue', 'Capital', 'Drawings'], 'Related revenue'],
    ['A provision for doubtful debts is created to:', ['Increase sales', 'Provide for expected credit losses', 'Reduce capital', 'Record cash purchases'], 'Provide for expected credit losses'],
  ],
  Law: [
    ['The doctrine of precedent means courts are guided by:', ['Past judicial decisions', 'Only customs', 'Newspaper reports', 'Private agreements'], 'Past judicial decisions'],
    ['An offer becomes a promise when it is:', ['Ignored', 'Accepted', 'Withdrawn', 'Advertised'], 'Accepted'],
    ['The writ used to produce a person unlawfully detained is:', ['Mandamus', 'Habeas corpus', 'Certiorari', 'Prohibition'], 'Habeas corpus'],
    ['The principle of natural justice includes:', ['Audi alteram partem', 'Caveat emptor only', 'Res judicata only', 'Nemo dat only'], 'Audi alteram partem'],
    ['A minor’s agreement is generally:', ['Valid', 'Void ab initio', 'Voidable at minor’s option', 'Illegal only'], 'Void ab initio'],
  ],
  Economics: [
    ['The law of demand assumes other factors remain:', ['Changing', 'Constant', 'Unknown', 'Negative'], 'Constant'],
    ['A market with many sellers and differentiated products is:', ['Perfect competition', 'Monopolistic competition', 'Monopoly', 'Duopoly'], 'Monopolistic competition'],
    ['The balance of payments records transactions between:', ['Citizens of one city', 'Residents and the rest of the world', 'Only banks', 'Only governments'], 'Residents and the rest of the world'],
    ['Marginal cost is the change in total cost due to one more unit of:', ['Price', 'Output', 'Income', 'Tax'], 'Output'],
    ['A progressive tax rate rises as:', ['Income rises', 'Income falls', 'Prices fall', 'Exports rise'], 'Income rises'],
  ],
  Taxation: [
    ['Input tax credit under GST allows a taxpayer to:', ['Claim credit for eligible tax paid on inputs', 'Avoid registration', 'Hide turnover', 'Remove invoices'], 'Claim credit for eligible tax paid on inputs'],
    ['PAN is primarily used to identify a:', ['Taxpayer', 'Product', 'Bank branch', 'Court'], 'Taxpayer'],
    ['TDS stands for:', ['Tax Deducted at Source', 'Total Duty System', 'Tax Deposit Scheme', 'Trade Data Service'], 'Tax Deducted at Source'],
    ['A tax invoice is issued for:', ['Taxable supply', 'Personal gift only', 'Loan repayment', 'Salary payment'], 'Taxable supply'],
    ['The financial year in India generally ends on:', ['31 March', '31 December', '30 June', '1 April'], '31 March'],
  ],
  History: [
    ['The Permanent Settlement was introduced by:', ['Lord Cornwallis', 'Lord Curzon', 'Lord Dalhousie', 'Lord Wellesley'], 'Lord Cornwallis'],
    ['The Cabinet Mission came to India in:', ['1942', '1945', '1946', '1947'], '1946'],
    ['The Harappan site famous for a dockyard is:', ['Lothal', 'Kalibangan', 'Mohenjo-daro', 'Ropar'], 'Lothal'],
    ['The Ilbert Bill controversy occurred during the viceroyalty of:', ['Lord Ripon', 'Lord Mayo', 'Lord Canning', 'Lord Lytton'], 'Lord Ripon'],
    ['The first session of the Indian National Congress was held at:', ['Bombay', 'Calcutta', 'Madras', 'Allahabad'], 'Bombay'],
  ],
  Geography: [
    ['The Coriolis force is caused by Earth’s:', ['Revolution only', 'Rotation', 'Tilt only', 'Gravity only'], 'Rotation'],
    ['El Niño is associated with abnormal warming of the:', ['Atlantic Ocean', 'Central and eastern Pacific Ocean', 'Indian Ocean only', 'Arctic Ocean'], 'Central and eastern Pacific Ocean'],
    ['The largest producer of mica in India has historically been:', ['Jharkhand', 'Punjab', 'Goa', 'Haryana'], 'Jharkhand'],
    ['The process of wearing away of soil by wind or water is:', ['Deposition', 'Erosion', 'Weathering only', 'Sedimentation'], 'Erosion'],
    ['Black soil is particularly suitable for:', ['Cotton', 'Tea', 'Jute', 'Wheat only'], 'Cotton'],
  ],
  Polity: [
    ['The power to amend the Constitution is provided under:', ['Article 368', 'Article 32', 'Article 356', 'Article 280'], 'Article 368'],
    ['The Finance Commission is constituted under:', ['Article 280', 'Article 324', 'Article 148', 'Article 123'], 'Article 280'],
    ['A Money Bill can be introduced only in:', ['Rajya Sabha', 'Lok Sabha', 'Either House', 'State Council'], 'Lok Sabha'],
    ['The Council of Ministers is collectively responsible to:', ['President', 'Lok Sabha', 'Rajya Sabha', 'Supreme Court'], 'Lok Sabha'],
    ['Fundamental Duties were added by the:', ['42nd Amendment', '44th Amendment', '1st Amendment', '73rd Amendment'], '42nd Amendment'],
  ],
  'General Science': [
    ['The SI unit of frequency is:', ['Hertz', 'Newton', 'Joule', 'Tesla'], 'Hertz'],
    ['Insulin is secreted by the:', ['Thyroid', 'Pancreas', 'Adrenal gland', 'Pituitary'], 'Pancreas'],
    ['The chemical formula of bleaching powder is commonly represented as:', ['CaOCl₂', 'NaHCO₃', 'CaCO₃', 'NaCl'], 'CaOCl₂'],
    ['A convex mirror is used as a rear-view mirror because it provides:', ['A wider field of view', 'A magnified real image', 'No image', 'An inverted large image'], 'A wider field of view'],
    ['The ozone layer protects life from:', ['Infrared rays', 'Ultraviolet rays', 'Radio waves', 'Sound waves'], 'Ultraviolet rays'],
  ],
  'Quantitative Aptitude': [
    ['A sum becomes ₹1,260 in 2 years at 12% simple interest. The principal is:', ['₹900', '₹1,000', '₹1,100', '₹1,200'], '₹1,000'],
    ['If a:b = 3:4 and b:c = 8:9, then a:c is:', ['2:3', '3:2', '4:3', '3:4'], '2:3'],
    ['A can complete a work in 12 days and B in 18 days. Together they complete it in:', ['6 days', '7.2 days', '9 days', '15 days'], '7.2 days'],
    ['The compound ratio of 2:3 and 4:5 is:', ['8:15', '6:20', '2:5', '4:15'], '8:15'],
    ['If a number is increased by 20% and then decreased by 20%, the net change is:', ['No change', '4% decrease', '4% increase', '8% decrease'], '4% decrease'],
  ],
  Reasoning: [
    ['Complete the series: 2, 6, 12, 20, 30, ?', ['36', '40', '42', '44'], '42'],
    ['If DELHI is coded as 73541, then HIDE is coded as:', ['4173', '4137', '4713', '1437'], '4173'],
    ['A clock shows 3:00. The angle between its hands is:', ['0°', '60°', '90°', '180°'], '90°'],
    ['Find the missing term: AZ, BY, CX, DW, ?', ['EV', 'FU', 'EW', 'EX'], 'EV'],
    ['If “+” means “×” and “−” means “+”, then 4 + 3 − 2 equals:', ['10', '12', '14', '20'], '14'],
  ],
  'General Awareness': [
    ['The headquarters of UNESCO is located in:', ['Paris', 'Geneva', 'New York', 'London'], 'Paris'],
    ['The Green Revolution in India is mainly associated with:', ['Food-grain production', 'Milk production', 'Fish production', 'Oil production'], 'Food-grain production'],
    ['The Reserve Bank of India issues:', ['Currency notes except one-rupee notes', 'All coins', 'Postage stamps', 'Passports'], 'Currency notes except one-rupee notes'],
    ['The national income of a country is measured for a:', ['Financial or accounting period', 'Single day', 'Single transaction', 'Political term only'], 'Financial or accounting period'],
    ['The headquarters of ISRO is in:', ['Bengaluru', 'Hyderabad', 'New Delhi', 'Ahmedabad'], 'Bengaluru'],
  ],
  'General Test': [
    ['A candidate scores 72 out of 90. The percentage is:', ['70%', '75%', '80%', '85%'], '80%'],
    ['If 5 machines make 500 units in 4 hours, 10 machines make in 4 hours:', ['500 units', '750 units', '1,000 units', '2,000 units'], '1,000 units'],
    ['The next term in 4, 9, 19, 39, ? is:', ['59', '69', '79', '89'], '79'],
    ['A statement assumed to be true for an argument is called:', ['Conclusion', 'Premise', 'Inference', 'Analogy'], 'Premise'],
    ['The median of 3, 8, 10, 12, 15 is:', ['8', '10', '12', '15'], '10'],
  ],
  'General Knowledge': [
    ['The Olympic Games are held once every:', ['2 years', '3 years', '4 years', '5 years'], '4 years'],
    ['The author of “Wings of Fire” is:', ['A.P.J. Abdul Kalam', 'R.K. Narayan', 'Vikram Seth', 'Chetan Bhagat'], 'A.P.J. Abdul Kalam'],
    ['The Siachen Glacier is located in the:', ['Karakoram Range', 'Aravalli Range', 'Western Ghats', 'Nilgiris'], 'Karakoram Range'],
    ['The world’s largest democracy is:', ['India', 'USA', 'Brazil', 'Indonesia'], 'India'],
    ['The National Science Day in India commemorates the discovery of:', ['Raman Effect', 'X-rays', 'Penicillin', 'Radioactivity'], 'Raman Effect'],
  ],
};

for (const [subject, extension] of Object.entries(questionExtensions)) {
  questionTemplateBanks[subject] = [...(questionTemplateBanks[subject] || []), ...extension];
}

const output = [];
const seenTexts = new Map();

function buildFreshStem(examLabel, subject, question, index) {
  return question;
}

for (const [examLabel, subjects] of Object.entries(examSubjects)) {
  const examKey = quizExamKeys[examLabel];
  for (const subject of subjects) {
    const bank = questionTemplateBanks[subject];
    if (!bank || bank.length < 20) {
      throw new Error(`Missing or incomplete bank for ${examLabel} / ${subject}`);
    }

    const usedTextSet = new Set();
    for (let idx = 0; idx < 20; idx += 1) {
      const [question, options, correctAnswer] = bank[idx];
      const freshQuestion = buildFreshStem(examLabel, subject, question, idx);
      const textKey = freshQuestion.trim().toLowerCase();
      if (usedTextSet.has(textKey)) {
        throw new Error(`Duplicate template text in ${subject}: ${question}`);
      }
      if (!Array.isArray(options) || options.length < 2 || !options.includes(correctAnswer)) {
        throw new Error(`Invalid answer options in ${examLabel} / ${subject}: ${question}`);
      }
      usedTextSet.add(textKey);
      const id = `v2-${String(examKey).toLowerCase()}-${String(subject).toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${idx + 1}`;
      if (seenTexts.has(id)) {
        throw new Error(`Duplicate id generated: ${id}`);
      }
      seenTexts.set(id, true);
      output.push({ id, exam: examKey, subject, question: freshQuestion, options, correctAnswer });
    }
  }
}

fs.writeFileSync('public/questions.json', `${JSON.stringify(output, null, 2)}\n`, 'utf8');

const summary = {};
for (const item of output) {
  summary[item.exam] ??= {};
  summary[item.exam][item.subject] = (summary[item.exam][item.subject] || 0) + 1;
}
console.log(`TOTAL=${output.length}`);
console.log(JSON.stringify(summary, null, 2));
