const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'public', 'questions.json');
const existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
const existingIds = new Set(existing.map((item) => item.id));

const examData = {
  CA: {
    Accounting: [
      ['The accounting equation is:', ['Assets = Liabilities + Capital', 'Assets + Liabilities = Capital', 'Assets = Capital - Liabilities', 'Liabilities = Assets + Capital'], 'Assets = Liabilities + Capital'],
      ['The process of recording financial transactions is called:', ['Posting', 'Journalising', 'Balancing', 'Auditing'], 'Journalising'],
      ['Goods withdrawn by the proprietor for personal use are called:', ['Sales return', 'Drawings', 'Purchases', 'Expenses'], 'Drawings'],
      ['The statement showing financial position at a point in time is:', ['Profit and Loss Account', 'Cash Flow Statement', 'Balance Sheet', 'Trial Balance'], 'Balance Sheet'],
      ['Depreciation is charged to:', ['Trading Account', 'Profit and Loss Account', 'Cash Account', 'Capital Account'], 'Profit and Loss Account'],
      ['Which book records all credit purchases?', ['Cash Book', 'Purchase Book', 'Sales Book', 'Journal Proper'], 'Purchase Book'],
      ['A debit balance in the bank passbook indicates:', ['Bank overdraft', 'Excess credit balance', 'No effect', 'Cash underflow'], 'Bank overdraft'],
      ['An asset converted into cash within a year is called:', ['Fixed asset', 'Current asset', 'Intangible asset', 'Fictitious asset'], 'Current asset'],
      ['The primary objective of accounting is to:', ['Reduce taxes', 'Record and communicate financial information', 'Avoid expenses', 'Increase liabilities'], 'Record and communicate financial information'],
      ['Bad debts are treated as:', ['Capital expenditure', 'Operating expense', 'Investing activity', 'Non-current liability'], 'Operating expense'],
      ['The trial balance is prepared to check:', ['Correctness of arithmetic of ledger balances', 'Cash flow timing', 'Market valuation', 'Tax impact'], 'Correctness of arithmetic of ledger balances'],
      ['A credit balance in a personal account means the holder is:', ['A debtor', 'A creditor', 'A banker', 'A shareholder'], 'A creditor'],
      ['The amount invested by the owner is called:', ['Loan', 'Drawings', 'Capital', 'Revenue'], 'Capital'],
      ['The financial statement used to understand liquidity is:', ['Cash flow statement', 'Balance sheet', 'Trading account', 'Income statement'], 'Cash flow statement'],
      ['The concept of recording at historical cost is known as:', ['Entity concept', 'Historical cost concept', 'Matching concept', 'Going concern'], 'Historical cost concept'],
    ],
    Law: [
      ['The Constitution of India came into force on:', ['15 August 1947', '26 January 1950', '2 October 1945', '1 January 1952'], '26 January 1950'],
      ['The Right to Equality is guaranteed under:', ['Article 14', 'Article 19', 'Article 21', 'Article 32'], 'Article 14'],
      ['The Supreme Court of India is the:', ['Highest appellate court', 'Only revenue court', 'Parliamentary body', 'Executive court'], 'Highest appellate court'],
      ['A contract is enforceable by:', ['Morality', 'Custom', 'Law', 'Society'], 'Law'],
      ['The head of the State in India is:', ['Prime Minister', 'President', 'Chief Justice', 'Attorney General'], 'President'],
      ['Rule of law is associated with:', ['Dicey', 'Marx', 'Hobbes', 'Aristotle'], 'Dicey'],
      ['The minimum age for President is:', ['18 years', '21 years', '25 years', '35 years'], '35 years'],
      ['A contract without free consent is:', ['Valid', 'Voidable', 'Void', 'Legal'], 'Voidable'],
      ['The Right to Freedom of Speech is in:', ['Article 19', 'Article 21', 'Article 17', 'Article 26'], 'Article 19'],
      ['A person entering into a contract is called a:', ['Witness', 'Party', 'Judge', 'Notary'], 'Party'],
      ['Judicial review in India is based on:', ['Separation of powers', 'Judicial supremacy', 'Federalism', 'Executive supremacy'], 'Judicial supremacy'],
      ['The concept of Directive Principles is inspired by:', ['USA', 'Britain', 'Ireland', 'Canada'], 'Ireland'],
      ['An agreement to do an impossible act is:', ['Valid', 'Void', 'Voidable', 'Enforceable'], 'Void'],
      ['The legal responsibility for a tort is imposed on:', ['The state only', 'The wrongdoer', 'The witness', 'The parliament'], 'The wrongdoer'],
      ['The Constitution is known as the:', ['Temporary law', 'Supreme law of the land', 'Executive order', 'Judicial opinion'], 'Supreme law of the land'],
    ],
    Economics: [
      ['Economics is mainly concerned with:', ['Wealth only', 'Human behaviour in relation to choices', 'Government control', 'Military strategy'], 'Human behaviour in relation to choices'],
      ['The fundamental economic problem is:', ['Inflation', 'Scarcity', 'Deflation', 'Monopoly'], 'Scarcity'],
      ['Demand falls when:', ['Price falls', 'Price rises', 'Income falls', 'Population falls'], 'Price rises'],
      ['GDP measures:', ['Total value of production', 'Government spending only', 'Tax revenue', 'Foreign trade'], 'Total value of production'],
      ['Inflation refers to:', ['Fall in prices', 'Rise in general price level', 'Stable prices', 'Decrease in wages'], 'Rise in general price level'],
      ['Opportunity cost means:', ['Cost of labour', 'Next best alternative forgone', 'Fixed cost', 'Marketing cost'], 'Next best alternative forgone'],
      ['The central bank of India is:', ['ICICI', 'SBI', 'RBI', 'PNB'], 'RBI'],
      ['Fiscal policy relates to:', ['Interest rate', 'Taxation and public expenditure', 'Currency supply', 'Import policy'], 'Taxation and public expenditure'],
      ['A market with one seller is called:', ['Monopoly', 'Oligopoly', 'Monopsony', 'Perfect competition'], 'Monopoly'],
      ['When total utility is maximum, marginal utility is:', ['Positive', 'Zero', 'Negative', 'Infinite'], 'Zero'],
      ['The main cause of unemployment is:', ['Low inflation', 'Lack of demand', 'High exports', 'Low taxes'], 'Lack of demand'],
      ['Elasticity of demand is:', ['Percentage change in quantity demanded over percentage change in price', 'Total revenue minus cost', 'Supply minus demand', 'Average cost'], 'Percentage change in quantity demanded over percentage change in price'],
      ['The primary sector includes:', ['Agriculture and mining', 'Manufacturing', 'Trade', 'Banking'], 'Agriculture and mining'],
      ['Equilibrium price is where:', ['Quantity demanded = quantity supplied', 'Demand is zero', 'Supply exceeds demand', 'Government fixes it'], 'Quantity demanded = quantity supplied'],
      ['The budget is prepared by:', ['RBI', 'Finance Ministry', 'SEBI', 'NITI Aayog'], 'Finance Ministry'],
    ],
    Taxation: [
      ['Income tax is a:', ['Indirect tax', 'Direct tax', 'Customs duty', 'Service tax'], 'Direct tax'],
      ['GST was implemented in India in:', ['2015', '2017', '2019', '2021'], '2017'],
      ['The tax collected by sellers and paid to government is:', ['Income tax', 'GST', 'Property tax', 'Wealth tax'], 'GST'],
      ['Tax burden of indirect taxes is usually borne by:', ['Government', 'Consumers', 'Employers', 'Investors'], 'Consumers'],
      ['Corporate tax is a:', ['Direct tax', 'Indirect tax', 'Excise duty', 'Custom duty'], 'Direct tax'],
      ['Tax evasion is:', ['Legal planning', 'Illegal non-payment of tax', 'Tax refund', 'Tax subsidy'], 'Illegal non-payment of tax'],
      ['The authority that collects GST in India is:', ['SEBI', 'RBI', 'CBIC', 'NSE'], 'CBIC'],
      ['Taxable income means:', ['Gross income before deductions', 'Total income minus deductions', 'Tax rate', 'Sales revenue'], 'Total income minus deductions'],
      ['Tax incidence refers to:', ['Who bears the burden of tax', 'Tax refund amount', 'Tax rate', 'Tax collection date'], 'Who bears the burden of tax'],
      ['Customs duty is imposed on:', ['Domestic sales', 'Goods imported', 'Salary', 'Bank deposits'], 'Goods imported'],
      ['The purpose of taxation is to:', ['Increase profits', 'Generate revenue for public expenditure', 'Reduce imports', 'Increase wages'], 'Generate revenue for public expenditure'],
      ['A tax on the supply of goods and services is:', ['Income tax', 'Property tax', 'GST', 'Gift tax'], 'GST'],
      ['The burden of indirect tax is generally on:', ['Producers only', 'Consumers', 'Government', 'Shareholders'], 'Consumers'],
      ['Taxable income can be reduced by:', ['Claiming deductions', 'Increasing sales', 'Borrowing', 'Ignoring income'], 'Claiming deductions'],
      ['Which is a direct tax?', ['GST', 'Corporate tax', 'VAT', 'Service tax'], 'Corporate tax'],
    ],
  },
  UPSC: {
    History: [
      ['The Indian National Congress was founded in:', ['1885', '1905', '1919', '1942'], '1885'],
      ['The Non-Cooperation Movement was launched in:', ['1919', '1920', '1928', '1930'], '1920'],
      ['The Great Revolt of 1857 began at:', ['Meerut', 'Lucknow', 'Jhansi', 'Gwalior'], 'Meerut'],
      ['The first battle of Panipat was fought in:', ['1526', '1556', '1618', '1761'], '1526'],
      ['The slogan “Do or Die” is associated with:', ['Quit India Movement', 'Civil Disobedience Movement', 'Home Rule Movement', 'Swadeshi Movement'], 'Quit India Movement'],
      ['Who wrote “Discovery of India”?', ['Subhas Bose', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Rabindranath Tagore'], 'Jawaharlal Nehru'],
      ['The Simon Commission was boycotted because it had:', ['No Indian representation', 'No British officers', 'No evidence', 'No report'], 'No Indian representation'],
      ['The first Mughal emperor was:', ['Akbar', 'Babur', 'Humayun', 'Aurangzeb'], 'Babur'],
      ['The Salt Satyagraha was led by:', ['Jawaharlal Nehru', 'Mahatma Gandhi', 'B.R. Ambedkar', 'Sardar Patel'], 'Mahatma Gandhi'],
      ['The Constitution came into force on:', ['15 August 1947', '26 January 1950', '26 November 1949', '1 April 1950'], '26 January 1950'],
      ['The title “Tiger of Mysore” was given to:', ['Tipu Sultan', 'Shivaji', 'Akbar', 'Aurangzeb'], 'Tipu Sultan'],
      ['Who was the last Mughal emperor?', ['Akbar', 'Bahadur Shah Zafar', 'Shah Jahan', 'Jahangir'], 'Bahadur Shah Zafar'],
      ['The Bhakti saint Kabir was associated with:', ['Brahmo Samaj', 'Sufism', 'Arya Samaj', 'Renaissance'], 'Sufism'],
      ['The famous Revolt of 1857 began in:', ['Kanpur', 'Meerut', 'Jhansi', 'Delhi'], 'Meerut'],
      ['The Quit India Movement started in:', ['1940', '1942', '1945', '1947'], '1942'],
    ],
    Geography: [
      ['The Himalayas are an example of:', ['Fold mountains', 'Block mountains', 'Volcanic mountains', 'Residual mountains'], 'Fold mountains'],
      ['The longest river in India is:', ['Godavari', 'Ganga', 'Indus', 'Brahmaputra'], 'Ganga'],
      ['The largest desert in India is:', ['Thar', 'Kalahari', 'Gobi', 'Sahara'], 'Thar'],
      ['Which state has the longest coastline?', ['Gujarat', 'Tamil Nadu', 'Kerala', 'Andhra Pradesh'], 'Gujarat'],
      ['The Tropic of Cancer passes through:', ['Gujarat', 'Kerala', 'Tamil Nadu', 'West Bengal'], 'Gujarat'],
      ['The highest waterfall in India is:', ['Jog Falls', 'Dudhsagar', 'Kunchikal', 'Nohkalikai'], 'Kunchikal'],
      ['The climate of India is shaped mainly by:', ['Monsoon and latitude', 'Polar winds only', 'Ocean currents only', 'Volcanic activity'], 'Monsoon and latitude'],
      ['The largest lake in India is:', ['Wular Lake', 'Chilka', 'Vembanad', 'Sambhar'], 'Wular Lake'],
      ['The Deccan Plateau is located in:', ['Northern India', 'Southern India', 'Eastern India', 'Western India'], 'Southern India'],
      ['Which soil is best for cotton?', ['Alluvial', 'Black', 'Laterite', 'Red'], 'Black'],
      ['Western disturbances cause:', ['Winter rainfall in North India', 'Monsoon winds', 'Coastal erosion', 'Desert storms'], 'Winter rainfall in North India'],
      ['The state called “Land of Five Rivers” is:', ['Punjab', 'Haryana', 'Jammu and Kashmir', 'Uttar Pradesh'], 'Punjab'],
      ['The Nilgiri Hills are in:', ['Tamil Nadu', 'Himachal Pradesh', 'Odisha', 'Arunachal'], 'Tamil Nadu'],
      ['The smallest state by area is:', ['Goa', 'Sikkim', 'Tripura', 'Manipur'], 'Goa'],
      ['The evergreen forests are mainly found in:', ['Western Ghats and North East', 'Thar', 'Indo-Gangetic plains', 'Himalayan region'], 'Western Ghats and North East'],
    ],
    Polity: [
      ['The Preamble begins with:', ['We the People of India', 'We the Citizens of India', 'We the Sovereign People', 'We the Nation'], 'We the People of India'],
      ['Right to Equality is in:', ['Article 14', 'Article 19', 'Article 21', 'Article 32'], 'Article 14'],
      ['The Constitutional head of the Union is:', ['Prime Minister', 'President', 'Chief Justice', 'Speaker'], 'President'],
      ['The Parliament consists of:', ['Lok Sabha and Rajya Sabha', 'Lok Sabha and Supreme Court', 'State Assemblies', 'Judiciary and Cabinet'], 'Lok Sabha and Rajya Sabha'],
      ['Directive Principles are borrowed from:', ['USA', 'Canada', 'Ireland', 'Britain'], 'Ireland'],
      ['Who appoints the Prime Minister?', ['Parliament', 'President', 'Supreme Court', 'Election Commission'], 'President'],
      ['Judicial review is exercised by:', ['Parliament', 'Executive', 'Judiciary', 'Election Commission'], 'Judiciary'],
      ['The Governor is appointed by:', ['Chief Minister', 'President', 'Prime Minister', 'Supreme Court'], 'President'],
      ['The CAG is appointed by:', ['President', 'Prime Minister', 'Parliament', 'Finance Ministry'], 'President'],
      ['Single citizenship exists in:', ['USA', 'Canada', 'India', 'Australia'], 'India'],
      ['The number of Schedules in the Constitution is:', ['11', '12', '13', '15'], '12'],
      ['The first session of the Constituent Assembly was held in:', ['1946', '1947', '1948', '1949'], '1946'],
      ['The phrase “Justice, Liberty, Equality, Fraternity” appears in:', ['Preamble', 'Directive Principles', 'Fundamental Duties', 'Federal Structure'], 'Preamble'],
      ['Which body conducts Lok Sabha elections?', ['Supreme Court', 'Election Commission', 'Parliamentary Committee', 'Cabinet'], 'Election Commission'],
      ['Right to Life is in:', ['Article 19', 'Article 21', 'Article 32', 'Article 51A'], 'Article 21'],
    ],
    Economics: [
      ['RBI was established in:', ['1934', '1947', '1956', '1969'], '1934'],
      ['GDP stands for:', ['Gross Domestic Product', 'General Development Product', 'Gross Domestic Progress', 'Global Development Pattern'], 'Gross Domestic Product'],
      ['Inflation means:', ['Fall in prices', 'Rise in general price level', 'Stable prices', 'Less money supply'], 'Rise in general price level'],
      ['Capital market instrument includes:', ['Savings account', 'Share', 'Bank deposit', 'Insurance premium'], 'Share'],
      ['Monetary policy is formulated by:', ['Finance Ministry', 'RBI', 'SEBI', 'NABARD'], 'RBI'],
      ['The primary sector includes:', ['Agriculture and mining', 'Banking', 'Transport', 'Manufacturing'], 'Agriculture and mining'],
      ['The budget is prepared by:', ['RBI', 'Finance Ministry', 'Election Commission', 'NITI Aayog'], 'Finance Ministry'],
      ['A rise in unemployment during recession is due to:', ['Higher exports', 'Decrease in demand', 'Higher taxes', 'Increased production'], 'Decrease in demand'],
      ['The study of production and distribution is:', ['Geography', 'Economics', 'Political science', 'Sociology'], 'Economics'],
      ['The price at equilibrium is:', ['Market price', 'Equilibrium price', 'Cost price', 'Opportunity price'], 'Equilibrium price'],
      ['Public good example is:', ['Private car', 'Clothes', 'National defence', 'Food grain'], 'National defence'],
      ['Opportunity cost is based on:', ['Scarcity of resources', 'Wages', 'Stable prices', 'Free goods'], 'Scarcity of resources'],
      ['The main source of revenue for the Union is:', ['Property tax', 'Custom duties', 'GST', 'State tax'], 'GST'],
      ['Fiscal deficit is:', ['Total expenditure minus total receipts excluding borrowing', 'Government savings', 'GDP', 'State revenue'], 'Total expenditure minus total receipts excluding borrowing'],
      ['The basic reason for economic scarcity is:', ['Unlimited wants and limited resources', 'Too much production', 'Low population', 'Low taxes'], 'Unlimited wants and limited resources'],
    ],
    'General Science': [
      ['Plants prepare food by:', ['Respiration', 'Photosynthesis', 'Transpiration', 'Fermentation'], 'Photosynthesis'],
      ['The SI unit of force is:', ['Joule', 'Newton', 'Pascal', 'Watt'], 'Newton'],
      ['Blood cells helping clotting are:', ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], 'Platelets'],
      ['Largest organ of human body is:', ['Liver', 'Lung', 'Skin', 'Stomach'], 'Skin'],
      ['Atomic number of carbon is:', ['6', '8', '12', '14'], '6'],
      ['The gas most abundant in atmosphere is:', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 'Nitrogen'],
      ['Speed of light is approx:', ['3 x 10^5 m/s', '3 x 10^8 m/s', '3 x 10^10 m/s', '3 x 10^2 m/s'], '3 x 10^8 m/s'],
      ['The powerhouse of the cell is:', ['Nucleus', 'Mitochondria', 'Golgi body', 'Ribosome'], 'Mitochondria'],
      ['Chemical formula of water is:', ['H2O2', 'HO2', 'H2O', 'OH2'], 'H2O'],
      ['Renewable energy source is:', ['Coal', 'Petroleum', 'Solar energy', 'Natural gas'], 'Solar energy'],
      ['Human heart has:', ['2 chambers', '3 chambers', '4 chambers', '5 chambers'], '4 chambers'],
      ['Vitamin produced by sunlight is:', ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], 'Vitamin D'],
      ['Liquid to vapour is:', ['Condensation', 'Evaporation', 'Fusion', 'Sublimation'], 'Evaporation'],
      ['Red planet is:', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 'Mars'],
      ['pH of pure water is:', ['0', '7', '10', '14'], '7'],
    ],
  },
  NDA: {
    Mathematics: [
      ['sin 90° is:', ['0', '1/2', '1', '√3/2'], '1'],
      ['If x + 2 = 7 then x is:', ['3', '4', '5', '6'], '5'],
      ['Slope of y = 3x + 2 is:', ['2', '3', '1/3', '-3'], '3'],
      ['Area of triangle with base 10 and height 6 is:', ['30', '60', '16', '24'], '30'],
      ['HCF of 12 and 18 is:', ['2', '3', '6', '9'], '6'],
      ['Sum of first 5 natural numbers is:', ['10', '15', '20', '25'], '15'],
      ['2^5 =', ['8', '16', '32', '64'], '32'],
      ['5! =', ['20', '60', '120', '720'], '120'],
      ['Circumference of circle radius 7 is:', ['14π', '21π', '28π', '49π'], '14π'],
      ['Polynomial of degree 2 is:', ['Linear', 'Quadratic', 'Cubic', 'Constant'], 'Quadratic'],
      ['Product of 3 and 7 is:', ['20', '21', '24', '28'], '21'],
      ['Median of 2, 5, 7, 9, 11 is:', ['5', '7', '9', '11'], '7'],
      ['If a = 2, b = 3 then a² + b² =', ['5', '10', '13', '25'], '13'],
      ['(0,0) is called:', ['Origin', 'Axis', 'Intercept', 'Vertex'], 'Origin'],
      ['Derivative of x² is:', ['x', '2x', 'x²', '2'], '2x'],
    ],
    English: [
      ['Synonym of brave is:', ['Cowardly', 'Fearless', 'Lazy', 'Weak'], 'Fearless'],
      ['Antonym of ancient is:', ['Old', 'Modern', 'Rich', 'Tall'], 'Modern'],
      ['She ___ to school every day.', ['go', 'goes', 'gone', 'going'], 'goes'],
      ['The red car is fast. Identify adjective:', ['car', 'red', 'fast', 'is'], 'red'],
      ['Plural of child is:', ['Childs', 'Childes', 'Children', 'Childrens'], 'Children'],
      ['Passive of “They completed the task” is:', ['The task is completed', 'The task was completed by them', 'They were completed', 'The task had completed'], 'The task was completed by them'],
      ['He is too weak ___ walk.', ['for', 'to', 'so', 'and'], 'to'],
      ['Correct spelling is:', ['Receved', 'Recieved', 'Received', 'Receeved'], 'Received'],
      ['A stitch in time saves nine means:', ['Delay is good', 'Prompt action prevents bigger problems', 'Time is money', 'Work is easy'], 'Prompt action prevents bigger problems'],
      ['___ apple a day keeps the doctor away.', ['A', 'An', 'The', 'No article'], 'An'],
      ['I have finished ___ work.', ['my', 'mine', 'me', 'I'], 'my'],
      ['If I ___ you, I would help.', ['am', 'was', 'were', 'be'], 'were'],
      ['Opposite of difficult is:', ['Hard', 'Easy', 'Strict', 'Heavy'], 'Easy'],
      ['Noun form of happy is:', ['Happily', 'Happiness', 'Happier', 'Happiest'], 'Happiness'],
      ['Correct sentence is:', ['He do not know', 'He does not know', 'He not know', 'He did not knew'], 'He does not know'],
    ],
    'General Science': [
      ['Which planet is called Morning Star?', ['Mercury', 'Venus', 'Mars', 'Jupiter'], 'Venus'],
      ['Force of attraction between Earth and objects is:', ['Magnetism', 'Gravity', 'Friction', 'Electricity'], 'Gravity'],
      ['Boiling point of water at sea level is:', ['90°C', '100°C', '110°C', '120°C'], '100°C'],
      ['Largest organ in human body is:', ['Brain', 'Liver', 'Skin', 'Heart'], 'Skin'],
      ['Which gas is essential for breathing?', ['Nitrogen', 'Oxygen', 'Helium', 'Neon'], 'Oxygen'],
      ['Vitamin needed for proper vision is:', ['Vitamin A', 'Vitamin C', 'Vitamin B', 'Vitamin K'], 'Vitamin A'],
      ['Most abundant gas in atmosphere is:', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], 'Nitrogen'],
      ['Study of living organisms is:', ['Geology', 'Biology', 'Chemistry', 'Physics'], 'Biology'],
      ['Chemical formula of carbon dioxide is:', ['CO', 'CO2', 'C2O', 'CO3'], 'CO2'],
      ['Part of plant that absorbs water is:', ['Stem', 'Leaf', 'Root', 'Flower'], 'Root'],
      ['SI unit of pressure is:', ['Newton', 'Joule', 'Pascal', 'Watt'], 'Pascal'],
      ['Liquid to solid is called:', ['Freezing', 'Melting', 'Evaporation', 'Condensation'], 'Freezing'],
      ['Who discovered penicillin?', ['Alexander Fleming', 'Isaac Newton', 'Marie Curie', 'Albert Einstein'], 'Alexander Fleming'],
      ['Gas released during photosynthesis is:', ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'], 'Oxygen'],
      ['Largest blood vessel is:', ['Vein', 'Capillary', 'Artery', 'Aorta'], 'Aorta'],
    ],
    History: [
      ['The first battle of Panipat was between Babur and:', ['Ibrahim Lodi', 'Sher Shah Suri', 'Rana Sanga', 'Humayun'], 'Ibrahim Lodi'],
      ['The founder of the Mughal Empire was:', ['Akbar', 'Babur', 'Humayun', 'Aurangzeb'], 'Babur'],
      ['The Chola dynasty is known for:', ['Naval power and temple architecture', 'Mughal art', 'British trade', 'Mauryan diplomacy'], 'Naval power and temple architecture'],
      ['Who was the last Mughal emperor?', ['Bahadur Shah Zafar', 'Aurangzeb', 'Shah Jahan', 'Akbar'], 'Bahadur Shah Zafar'],
      ['The Battle of Plassey was fought in:', ['1757', '1761', '1773', '1857'], '1757'],
      ['The Indian National Army was formed by:', ['Subhas Bose', 'Bhagat Singh', 'Sardar Patel', 'C. Rajagopalachari'], 'Subhas Bose'],
      ['Who led the Dandi March?', ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Bal Gangadhar Tilak', 'Lala Lajpat Rai'], 'Mahatma Gandhi'],
      ['The Quit India Movement began in:', ['1940', '1942', '1945', '1947'], '1942'],
      ['Which emperor built the Taj Mahal?', ['Shah Jahan', 'Akbar', 'Aurangzeb', 'Jahangir'], 'Shah Jahan'],
      ['The “Iron Man of India” is:', ['Jawaharlal Nehru', 'Sardar Vallabhbhai Patel', 'Bhagat Singh', 'Rajendra Prasad'], 'Sardar Vallabhbhai Patel'],
      ['Nalanda University was in:', ['Bihar', 'Uttar Pradesh', 'Tamil Nadu', 'Maharashtra'], 'Bihar'],
      ['The Khilafat Movement supported:', ['The Ottoman Caliphate', 'The British Crown', 'The Mughal Empire', 'The National Congress'], 'The Ottoman Caliphate'],
      ['The Kalinga War was fought by:', ['Chandragupta Maurya', 'Ashoka', 'Harsha', 'Samudragupta'], 'Ashoka'],
      ['The title “Vandemataram” was popularised by:', ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Sarojini Naidu', 'Mahatma Gandhi'], 'Bankim Chandra Chattopadhyay'],
      ['Who was the first Mughal emperor?', ['Babur', 'Akbar', 'Humayun', 'Jahangir'], 'Babur'],
    ],
    Geography: [
      ['Capital of India is:', ['Mumbai', 'Delhi', 'Kolkata', 'Chennai'], 'Delhi'],
      ['Largest ocean is:', ['Atlantic', 'Indian', 'Pacific', 'Arctic'], 'Pacific'],
      ['Highest mountain peak is:', ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], 'Mount Everest'],
      ['Equator divides Earth into:', ['Eastern and western', 'Northern and southern', 'Tropical and polar', 'Arctic and Antarctic'], 'Northern and southern'],
      ['Brahmaputra flows through:', ['India and Bangladesh', 'India and Nepal', 'Pakistan and Afghanistan', 'Sri Lanka and India'], 'India and Bangladesh'],
      ['Cherrapunji is famous for:', ['Highest rainfall', 'Desert', 'Coral reefs', 'Volcanoes'], 'Highest rainfall'],
      ['Great Indian Desert is known as:', ['Gobi', 'Kalahari', 'Thar', 'Sahara'], 'Thar'],
      ['State with highest population is:', ['Maharashtra', 'Uttar Pradesh', 'Bihar', 'West Bengal'], 'Uttar Pradesh'],
      ['Central plateau region is called:', ['Vindhya', 'Deccan Plateau', 'Tibetan Plateau', 'Patagonia'], 'Deccan Plateau'],
      ['Pink City is:', ['Jaipur', 'Jodhpur', 'Udaipur', 'Bikaner'], 'Jaipur'],
      ['Tropic of Cancer latitude is:', ['0°', '23.5°N', '66.5°N', '90°N'], '23.5°N'],
      ['Western coast is known for:', ['Backwaters and beaches', 'Snowfields', 'Desert', 'Steppes'], 'Backwaters and beaches'],
      ['Largest delta is:', ['Sundarbans', 'Nile', 'Mississippi', 'Amazon'], 'Sundarbans'],
      ['Longest river in the world is:', ['Nile', 'Amazon', 'Yangtze', 'Mississippi'], 'Amazon'],
      ['The longest international border in India is with:', ['Pakistan', 'China', 'Bangladesh', 'Nepal'], 'Bangladesh'],
    ],
  },
  SSC: {
    'Quantitative Aptitude': [
      ['Average of 4, 6, 8, 10 is:', ['6', '7', '8', '9'], '7'],
      ['25% of 200 is:', ['25', '50', '75', '100'], '50'],
      ['60 km/h for 180 km takes:', ['2 hours', '3 hours', '4 hours', '5 hours'], '3 hours'],
      ['If 8x = 32 then x is:', ['2', '3', '4', '5'], '4'],
      ['Simple interest on ₹1000 at 10% for 2 years is:', ['₹100', '₹200', '₹300', '₹400'], '₹200'],
      ['The ratio of 12 to 18 is:', ['2:3', '3:2', '1:2', '4:3'], '2:3'],
      ['Perimeter of a 5 cm by 3 cm rectangle is:', ['8 cm', '12 cm', '15 cm', '16 cm'], '16 cm'],
      ['The square of 9 is:', ['18', '27', '81', '99'], '81'],
      ['The cube root of 64 is:', ['2', '4', '6', '8'], '4'],
      ['Probability of head on fair coin toss is:', ['0', '1/2', '1', '2'], '1/2'],
      ['If a = 5, b = 3, then a² - b² = ?', ['8', '12', '16', '25'], '16'],
      ['The cost price of an item sold for ₹120 at a 20% profit is:', ['₹90', '₹100', '₹110', '₹120'], '₹100'],
      ['The LCM of 6 and 8 is:', ['12', '18', '24', '48'], '24'],
      ['The value of 7 × 8 ÷ 2 is:', ['14', '28', '56', '7'], '28'],
      ['15% of 200 is:', ['15', '20', '30', '40'], '30'],
    ],
    Reasoning: [
      ['Odd one out: 2, 3, 5, 7, 9', ['2', '3', '5', '9'], '9'],
      ['A is taller than B and B is taller than C. Who is tallest?', ['A', 'B', 'C', 'Cannot say'], 'A'],
      ['Complete the series: 3, 6, 9, 12, ?', ['13', '14', '15', '16'], '15'],
      ['Which is a vowel?', ['B', 'C', 'E', 'M'], 'E'],
      ['If all roses are flowers and some flowers are red, which statement is definitely true?', ['All roses are red', 'Some roses are red', 'All flowers are roses', 'Some flowers are roses'], 'Some flowers are roses'],
      ['Arrange in logical order: Seed, Plant, Flower, Fruit', ['Seed, Flower, Plant, Fruit', 'Seed, Plant, Flower, Fruit', 'Flower, Seed, Plant, Fruit', 'Plant, Seed, Flower, Fruit'], 'Seed, Plant, Flower, Fruit'],
      ['Which number comes next: 1, 4, 9, 16, ?', ['20', '24', '25', '36'], '25'],
      ['If 1 = A, 2 = B, 3 = C, then 4 = ?', ['D', 'E', 'F', 'G'], 'D'],
      ['Pointing to a girl, Raj says, “She is my sister’s daughter.” How is the girl related to Raj?', ['Daughter', 'Niece', 'Cousin', 'Granddaughter'], 'Niece'],
      ['Choose the odd one out: Sun, Moon, Earth, Mars', ['Sun', 'Moon', 'Earth', 'Mars'], 'Moon'],
      ['Which comes next: AB, CD, EF, ?', ['GH', 'IJ', 'KL', 'MN'], 'GH'],
      ['If today is Monday, what day will it be after 10 days?', ['Tuesday', 'Wednesday', 'Thursday', 'Friday'], 'Thursday'],
      ['Which word does not belong: Book, Pen, Table, Paper', ['Book', 'Pen', 'Table', 'Paper'], 'Table'],
      ['If all dogs bark and Max is a dog, then:', ['Max does not bark', 'Max can bark', 'Max is a cat', 'Max sings'], 'Max can bark'],
      ['Find the missing number: 5, 10, 20, 40, ?', ['50', '60', '80', '100'], '80'],
    ],
    English: [
      ['Pick the correct synonym of “rapid”.', ['Slow', 'Quick', 'Heavy', 'Tiny'], 'Quick'],
      ['He ___ in Delhi for five years.', ['lives', 'live', 'living', 'has lived'], 'has lived'],
      ['Choose the correct article: ___ honest man.', ['A', 'An', 'The', 'No article'], 'An'],
      ['The opposite of “visible” is:', ['Clear', 'Invisible', 'Present', 'Bright'], 'Invisible'],
      ['Select the correct spelling:', ['Accesible', 'Accessible', 'Acessible', 'Accesable'], 'Accessible'],
      ['The noun form of “strong” is:', ['Strength', 'Strongly', 'Stronger', 'Strongerly'], 'Strength'],
      ['The plural of “thesis” is:', ['Thesises', 'Thesis', 'Thesies', 'Theses'], 'Theses'],
      ['He said, “I am tired.” Change into indirect speech.', ['He said that he is tired', 'He said that he was tired', 'He said that I am tired', 'He said he tired'], 'He said that he was tired'],
      ['Choose the correct sentence:', ['She do not like tea', 'She does not like tea', 'She not like tea', 'She is not like tea'], 'She does not like tea'],
      ['The synonym of “happy” is:', ['Sad', 'Joyful', 'Angry', 'Tired'], 'Joyful'],
      ['Fill in the blank: I am looking forward ___ you.', ['for', 'to', 'at', 'with'], 'to'],
      ['Which is a collective noun?', ['Gold', 'Bravery', 'Team', 'Honesty'], 'Team'],
      ['He is ___ honest man.', ['a', 'an', 'the', 'no article'], 'an'],
      ['The correct passive of “The teacher praised the boy” is:', ['The boy was praised by the teacher', 'The boy praised the teacher', 'The teacher was praised by the boy', 'The boy is praised by teacher'], 'The boy was praised by the teacher'],
      ['Choose the correct word: She has ___ apples in the basket.', ['a little', 'much', 'many', 'some'], 'many'],
    ],
    'General Awareness': [
      ['Who is known as the Father of the Nation in India?', ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'Bhagat Singh'], 'Mahatma Gandhi'],
      ['The capital of Japan is:', ['Seoul', 'Tokyo', 'Beijing', 'Bangkok'], 'Tokyo'],
      ['The currency of the United Kingdom is:', ['Dollar', 'Euro', 'Pound Sterling', 'Yen'], 'Pound Sterling'],
      ['The largest planet in the solar system is:', ['Earth', 'Mars', 'Jupiter', 'Saturn'], 'Jupiter'],
      ['Who wrote the National Anthem “Jana Gana Mana”?', ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarojini Naidu', 'Subhas Chandra Bose'], 'Rabindranath Tagore'],
      ['The headquarters of the United Nations is in:', ['Geneva', 'New York', 'Paris', 'Rome'], 'New York'],
      ['Which is the largest mammal?', ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'], 'Blue whale'],
      ['Who is known as the Missile Man of India?', ['APJ Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha', 'Raja Ramanna'], 'APJ Abdul Kalam'],
      ['The longest river in the world is:', ['Nile', 'Amazon', 'Ganga', 'Yangtze'], 'Amazon'],
      ['Which gas do plants absorb?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 'Carbon dioxide'],
      ['The Parliament of India is located in:', ['Mumbai', 'New Delhi', 'Chennai', 'Kolkata'], 'New Delhi'],
      ['The term “Bharat” appears in the constitution in:', ['Preamble', 'Fundamental Rights', 'Directive Principles', 'Schedules'], 'Preamble'],
      ['Who discovered gravity?', ['Galileo', 'Newton', 'Einstein', 'Kepler'], 'Newton'],
      ['The smallest continent is:', ['Europe', 'Australia', 'Antarctica', 'South America'], 'Australia'],
      ['The number of states in India is:', ['24', '28', '29', '30'], '28'],
    ],
  },
  CUET: {
    'General Test': [
      ['If 12 workers complete a task in 8 days, how many days will 6 workers take?', ['12 days', '14 days', '16 days', '18 days'], '16 days'],
      ['The average of 10, 20, 30 is:', ['15', '20', '25', '30'], '20'],
      ['A train runs at 72 km/h. In 15 minutes it covers:', ['12 km', '18 km', '24 km', '30 km'], '18 km'],
      ['Which is the next term: 1, 3, 6, 10, 15, ?', ['20', '21', '24', '25'], '21'],
      ['The percentage equivalent of 1/4 is:', ['20%', '25%', '50%', '75%'], '25%'],
      ['A shopkeeper marks a product at ₹500 and gives 10% discount. Selling price is:', ['₹450', '₹470', '₹480', '₹490'], '₹450'],
      ['The HCF of 18 and 24 is:', ['2', '3', '6', '12'], '6'],
      ['Which is the odd one out: 8, 27, 64, 125, 216?', ['8', '27', '64', '216'], '216'],
      ['If all men are honest and Ravi is a man, Ravi is:', ['dishonest', 'honest', 'rich', 'poor'], 'honest'],
      ['Which of the following is a prime number?', ['21', '29', '33', '39'], '29'],
      ['The area of a square with side 5 cm is:', ['10 cm²', '20 cm²', '25 cm²', '30 cm²'], '25 cm²'],
      ['The correct order of the planets from the sun is:', ['Mercury, Venus, Earth, Mars', 'Venus, Mercury, Earth, Mars', 'Earth, Venus, Mercury, Mars', 'Mars, Earth, Venus, Mercury'], 'Mercury, Venus, Earth, Mars'],
      ['Which word is the opposite of “sincere”?', ['Honest', 'Dishonest', 'Trustworthy', 'Friendly'], 'Dishonest'],
      ['The value of 15 × 2 + 10 is:', ['20', '25', '30', '40'], '40'],
      ['If north is opposite to south, then east is opposite to:', ['North', 'South', 'West', 'East'], 'West'],
    ],
    English: [
      ['Choose the correct synonym of “brisk”.', ['Slow', 'Quick', 'Weak', 'Heavy'], 'Quick'],
      ['Complete the sentence: He ___ a new book yesterday.', ['buy', 'buys', 'bought', 'buying'], 'bought'],
      ['The antonym of “generous” is:', ['Kind', 'Selfish', 'Polite', 'Mild'], 'Selfish'],
      ['Choose the correct spelling:', ['Seperate', 'Separate', 'Seperete', 'Separete'], 'Separate'],
      ['The noun form of “teach” is:', ['Teacher', 'Teaching', 'Taught', 'Teachable'], 'Teaching'],
      ['Which sentence is correct?', ['He go to school', 'He goes to school', 'He going to school', 'He gone to school'], 'He goes to school'],
      ['Fill in the blank: She is good ___ English.', ['in', 'at', 'on', 'for'], 'at'],
      ['One who cannot read or write is called:', ['Scholar', 'Illiterate', 'Weak', 'Teacher'], 'Illiterate'],
      ['Change into passive: “The people elected him.”', ['He was elected by the people', 'He is elected by people', 'He elected the people', 'He is electing the people'], 'He was elected by the people'],
      ['Choose the correct article: ___ umbrella is on the table.', ['A', 'An', 'The', 'No article'], 'The'],
      ['The plural of “mouse” is:', ['Mouses', 'Mice', 'Mousees', 'Mices'], 'Mice'],
      ['Select the correct indirect speech: He said, “I am late.”', ['He said that he was late', 'He said that he is late', 'He says that he was late', 'He said he late'], 'He said that he was late'],
      ['The opposite of “advantage” is:', ['Profit', 'Disadvantage', 'Benefit', 'Gain'], 'Disadvantage'],
      ['Identify the adjective in: “The blue sky looked beautiful.”', ['sky', 'looked', 'blue', 'beautiful'], 'blue'],
      ['Choose the correct word: She has ___ apples in the basket.', ['a little', 'much', 'many', 'some'], 'many'],
    ],
    'General Knowledge': [
      ['Who is the current President of India?', ['Ram Nath Kovind', 'Pratibha Patil', 'Droupadi Murmu', 'Narendra Modi'], 'Droupadi Murmu'],
      ['The capital of Karnataka is:', ['Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru'], 'Bengaluru'],
      ['The currency of France is:', ['Dollar', 'Rupee', 'Euro', 'Yen'], 'Euro'],
      ['The largest river in India is:', ['Yamuna', 'Ganga', 'Godavari', 'Krishna'], 'Ganga'],
      ['The national animal of India is:', ['Lion', 'Tiger', 'Elephant', 'Gaur'], 'Tiger'],
      ['Who painted the Mona Lisa?', ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'], 'Leonardo da Vinci'],
      ['The smallest planet in the solar system is:', ['Mercury', 'Mars', 'Venus', 'Earth'], 'Mercury'],
      ['The headquarters of the World Health Organization is in:', ['Geneva', 'Paris', 'Rome', 'New York'], 'Geneva'],
      ['The national game of India is:', ['Cricket', 'Hockey', 'Football', 'Kabaddi'], 'Hockey'],
      ['Which festival is known as the festival of lights?', ['Holi', 'Diwali', 'Navratri', 'Id'], 'Diwali'],
      ['Who discovered radioactivity?', ['Marie Curie', 'Isaac Newton', 'Albert Einstein', 'Rosalind Franklin'], 'Marie Curie'],
      ['The largest continent is:', ['Africa', 'Europe', 'Asia', 'North America'], 'Asia'],
      ['The first man to walk on the moon was:', ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], 'Neil Armstrong'],
      ['The national bird of India is:', ['Peacock', 'Parrot', 'Eagle', 'Sparrow'], 'Peacock'],
      ['The Indian Constitution came into effect on:', ['15 August 1947', '26 January 1950', '2 October 1945', '1 January 1948'], '26 January 1950'],
    ],
    Reasoning: [
      ['If all pens are instruments and some instruments are blue, which statement is definitely true?', ['All pens are blue', 'Some pens are blue', 'All instruments are pens', 'Some instruments are pens'], 'Some instruments are pens'],
      ['What comes next: 2, 4, 8, 16, ?', ['20', '24', '32', '64'], '32'],
      ['Which of the following is a palindrome?', ['level', 'apple', 'orange', 'mango'], 'level'],
      ['Arrange in ascending order: 0.5, 0.25, 1, 0.75', ['0.25, 0.5, 0.75, 1', '0.5, 0.25, 1, 0.75', '1, 0.75, 0.5, 0.25', '0.75, 0.5, 1, 0.25'], '0.25, 0.5, 0.75, 1'],
      ['Choose the odd one out: Table, Chair, Book, Sofa', ['Table', 'Chair', 'Book', 'Sofa'], 'Book'],
      ['If P is father of Q and Q is father of R, then P is the ___ of R.', ['Grandfather', 'Father', 'Brother', 'Uncle'], 'Grandfather'],
      ['The next letter in the series A, C, F, J, ? is:', ['K', 'L', 'O', 'P'], 'O'],
      ['If 12 = 3 and 18 = 6, then 24 = ?', ['8', '9', '10', '12'], '8'],
      ['Find the odd one out: Red, Blue, Green, Square', ['Red', 'Blue', 'Green', 'Square'], 'Square'],
      ['Select the missing number: 5, 9, 14, 23, ?', ['30', '32', '37', '40'], '37'],
      ['If you rotate a clock 90° clockwise, which hand position changes most?', ['Hour hand', 'Minute hand', 'Second hand', 'All equally'], 'Minute hand'],
      ['Which pair is analogous: Triangle : Polygon ?', ['Dog : Pet', 'Book : Writer', 'River : Flow', 'Apple : Fruit'], 'Apple : Fruit'],
      ['If today is Tuesday, what day was it 3 days ago?', ['Monday', 'Friday', 'Saturday', 'Sunday'], 'Saturday'],
      ['The word “CART” arranged in a different pattern is:', ['RATC', 'TRACT', 'CRAT', 'RACT'], 'TRACT'],
      ['One of the following is a contradiction: A is A, A is not A, A is B, B is C', ['A is A', 'A is not A', 'A is B', 'B is C'], 'A is not A'],
    ],
    Mathematics: [
      ['The value of 12² is:', ['24', '120', '144', '169'], '144'],
      ['The simple interest on ₹2000 at 8% for 1 year is:', ['₹80', '₹160', '₹200', '₹240'], '₹160'],
      ['Solve: 3x = 21', ['4', '5', '6', '7'], '7'],
      ['The area of a rectangle 8 m by 5 m is:', ['13 m²', '26 m²', '40 m²', '45 m²'], '40 m²'],
      ['The sum of angles of a triangle is:', ['90°', '180°', '270°', '360°'], '180°'],
      ['Find the median of 4, 7, 8, 10, 12:', ['4', '7', '8', '10'], '8'],
      ['Which one is greater: 0.6 or 0.55?', ['0.55', '0.6', 'equal', 'none'], '0.6'],
      ['The value of 9 ÷ 3 + 2 is:', ['3', '5', '6', '7'], '5'],
      ['The LCM of 4 and 6 is:', ['8', '12', '18', '24'], '12'],
      ['If a = 2, b = 3, then a + b × 2 = ?', ['8', '10', '12', '14'], '8'],
      ['The circumference of a circle of radius 7 is:', ['7π', '14π', '21π', '49π'], '14π'],
      ['The number of edges in a cube is:', ['6', '8', '10', '12'], '12'],
      ['If x = 5 and y = 2, then x² - y² = ?', ['9', '15', '21', '25'], '21'],
      ['The value of √81 is:', ['7', '8', '9', '10'], '9'],
      ['A triangle with all sides equal is called:', ['Scalene', 'Isosceles', 'Equilateral', 'Right'], 'Equilateral'],
    ],
  },
};

const newItems = [];
for (const [exam, subjectMap] of Object.entries(examData)) {
  for (const [subject, questionList] of Object.entries(subjectMap)) {
    questionList.forEach(([question, options, correctAnswer], index) => {
      const id = `${exam.toLowerCase()}-${subject.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${index + 1}`;
      if (!existingIds.has(id)) {
        newItems.push({ id, exam, subject, question, options, correctAnswer });
        existingIds.add(id);
      }
    });
  }
}

const merged = [...existing, ...newItems];
fs.writeFileSync(filePath, JSON.stringify(merged, null, 2) + '\n', 'utf8');

const summary = {};
for (const item of merged) {
  if (!summary[item.exam]) summary[item.exam] = {};
  summary[item.exam][item.subject] = (summary[item.exam][item.subject] || 0) + 1;
}
console.log('Total questions:', merged.length);
console.log(JSON.stringify(summary, null, 2));
